from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_menu(object):

    def combo_binding(column, table, id_column, id_value):
        conn, cursor = sqlite3.connect("Our_data.db")
        query ='''SELECT  FROM  WHERE  = '''.format(column, table, id_column, id_value)
        temp_list = []
        try:
            cursor.execute(query)
            row = cursor.fetchall()
            for i in range(len(row)):
                temp_list.append(row[i][0])

            del row
            return temp_list

        except sqlite3.Error as e:
            print(e)

        finally:
            cursor.close()
            conn.close()
            del conn, cursor, query

    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(1919, 1069)
        menu.setStyleSheet("")
        self.listView = QtWidgets.QListView(menu)
        self.listView.setGeometry(QtCore.QRect(0, 560, 601, 511))
        self.listView.setAutoFillBackground(False)
        self.listView.setStyleSheet("QListView{ \n"
"border-image: url(wfl1.jpg);\n"
"background-color :rgb(224, 255, 219);\n"
"color rgb(251, 255, 207);\n"
"}")
        self.listView.setObjectName("listView")
        self.frame = QtWidgets.QFrame(menu)
        self.frame.setGeometry(QtCore.QRect(0, 50, 601, 511))
        self.frame.setStyleSheet("background-image: url(frnstlc.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.checkBoxgullac = QtWidgets.QCheckBox(self.frame)
        self.checkBoxgullac.setGeometry(QtCore.QRect(20, 110, 175, 27))
        self.checkBoxgullac.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBoxgullac.setObjectName("checkBoxgullac")
        self.checkBoxirmik = QtWidgets.QCheckBox(self.frame)
        self.checkBoxirmik.setGeometry(QtCore.QRect(310, 70, 221, 27))
        self.checkBoxirmik.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBoxirmik.setObjectName("checkBoxirmik")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 0, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBoxkazandibi = QtWidgets.QCheckBox(self.frame)
        self.checkBoxkazandibi.setGeometry(QtCore.QRect(20, 170, 175, 27))
        self.checkBoxkazandibi.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBoxkazandibi.setObjectName("checkBoxkazandibi")
        self.checkBoxprofiterol = QtWidgets.QCheckBox(self.frame)
        self.checkBoxprofiterol.setGeometry(QtCore.QRect(310, 100, 175, 27))
        self.checkBoxprofiterol.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBoxprofiterol.setObjectName("checkBoxprofiterol")
        self.checkBoxspungle = QtWidgets.QCheckBox(self.frame)
        self.checkBoxspungle.setGeometry(QtCore.QRect(310, 130, 175, 27))
        self.checkBoxspungle.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBoxspungle.setObjectName("checkBoxspungle")
        self.checboxmagnolia = QtWidgets.QCheckBox(self.frame)
        self.checboxmagnolia.setGeometry(QtCore.QRect(310, 40, 175, 27))
        self.checboxmagnolia.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checboxmagnolia.setObjectName("checboxmagnolia")

        self.checkboxmuhallebi = QtWidgets.QCheckBox(self.frame)
        self.checkboxmuhallebi.setGeometry(QtCore.QRect(20, 140, 175, 27))
        self.checkboxmuhallebi.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkboxmuhallebi.setObjectName("checkboxmuhallebi")
        self.checkBoxsutlac = QtWidgets.QCheckBox(self.frame)
        self.checkBoxsutlac.setGeometry(QtCore.QRect(20, 50, 175, 27))
        self.checkBoxsutlac.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBoxsutlac.setObjectName("checkBoxsutlac")

        self.checkBoxTrilece = QtWidgets.QCheckBox(self.frame)
        self.checkBoxTrilece.setGeometry(QtCore.QRect(20, 80, 175, 27))
        self.checkBoxTrilece.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBoxTrilece.setObjectName("checkBoxTrilece")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(450, 10, 141, 21))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.checkBoxkeskul = QtWidgets.QCheckBox(self.frame)
        self.checkBoxkeskul.setGeometry(QtCore.QRect(310, 160, 175, 27))
        self.checkBoxkeskul.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBoxkeskul.setObjectName("checkBoxkeskul")
        self.cmboxmagnolia = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmboxmagnolia.setGeometry(QtCore.QRect(540, 40, 51, 22))
        self.cmboxmagnolia.setObjectName("cmboxmagnolia")
        self.cmboxmagnolia.addItem("")
        self.cmboxmagnolia.addItem("")
        self.cmboxmagnolia.addItem("")
        self.cmboxmagnolia.addItem("")
        self.cmboxmagnolia.addItem("")
        self.cmboxirmik = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmboxirmik.setGeometry(QtCore.QRect(540, 70, 51, 22))
        self.cmboxirmik.setObjectName("cmboxirmik")
        self.cmboxirmik.addItem("")
        self.cmboxirmik.addItem("")
        self.cmboxirmik.addItem("")
        self.cmboxirmik.addItem("")
        self.cmboxirmik.addItem("")
        self.cmboxprofiterol = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmboxprofiterol.setGeometry(QtCore.QRect(540, 100, 51, 22))
        self.cmboxprofiterol.setObjectName("cmboxprofiterol")
        self.cmboxprofiterol.addItem("")
        self.cmboxprofiterol.addItem("")
        self.cmboxprofiterol.addItem("")
        self.cmboxprofiterol.addItem("")
        self.cmboxprofiterol.addItem("")
        self.cmboxmagnolia_4 = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmboxmagnolia_4.setGeometry(QtCore.QRect(540, 130, 51, 22))
        self.cmboxmagnolia_4.setObjectName("cmboxmagnolia_4")
        self.cmboxmagnolia_4.addItem("")
        self.cmboxmagnolia_4.addItem("")
        self.cmboxmagnolia_4.addItem("")
        self.cmboxmagnolia_4.addItem("")
        self.cmboxmagnolia_4.addItem("")
        self.cmboxmagnolia_5 = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmboxmagnolia_5.setGeometry(QtCore.QRect(540, 160, 51, 22))
        self.cmboxmagnolia_5.setObjectName("cmboxmagnolia_5")
        self.cmboxmagnolia_5.addItem("")
        self.cmboxmagnolia_5.addItem("")
        self.cmboxmagnolia_5.addItem("")
        self.cmboxmagnolia_5.addItem("")
        self.cmboxmagnolia_5.addItem("")
        self.cmboxsutlac = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmboxsutlac.setGeometry(QtCore.QRect(210, 50, 71, 20))
        self.cmboxsutlac.setObjectName("cmboxsutlac")
        self.cmboxsutlac.addItem("")
        self.cmboxsutlac.addItem("")
        self.cmboxsutlac.addItem("")
        self.cmboxsutlac.addItem("")
        self.cmboxsutlac.addItem("")
        self.cmbBoxTrilece = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmbBoxTrilece.setGeometry(QtCore.QRect(210, 80, 71, 20))
        self.cmbBoxTrilece.setObjectName("cmbBoxTrilece")
        self.cmbBoxTrilece.addItem("")
        self.cmbBoxTrilece.addItem("")
        self.cmbBoxTrilece.addItem("")
        self.cmbBoxTrilece.addItem("")
        self.cmbBoxTrilece.addItem("")
        self.cmbboxgullac = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmbboxgullac.setGeometry(QtCore.QRect(210, 110, 71, 20))
        self.cmbboxgullac.setObjectName("cmbboxgullac")
        self.cmbboxgullac.addItem("")
        self.cmbboxgullac.addItem("")
        self.cmbboxgullac.addItem("")
        self.cmbboxgullac.addItem("")
        self.cmbboxgullac.addItem("")
        self.cmbboxmuhallebi = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmbboxmuhallebi.setGeometry(QtCore.QRect(210, 140, 71, 20))
        self.cmbboxmuhallebi.setObjectName("cmbboxmuhallebi")
        self.cmbboxmuhallebi.addItem("")
        self.cmbboxmuhallebi.addItem("")
        self.cmbboxmuhallebi.addItem("")
        self.cmbboxmuhallebi.addItem("")
        self.cmbboxmuhallebi.addItem("")
        self.cmbboxkazandibi = QtWidgets.Qcmboxmagnolia(self.frame)
        self.cmbboxkazandibi.setGeometry(QtCore.QRect(210, 170, 71, 20))
        self.cmbboxkazandibi.setObjectName("cmbboxkazandibi")
        self.cmbboxkazandibi.addItem("")
        self.cmbboxkazandibi.addItem("")
        self.cmbboxkazandibi.addItem("")
        self.cmbboxkazandibi.addItem("")
        self.cmbboxkazandibi.addItem("")
        self.widget_2 = QtWidgets.QWidget(menu)
        self.widget_2.setGeometry(QtCore.QRect(0, 610, 601, 171))
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setObjectName("widget_2")
        self.checkBox_20 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_20.setGeometry(QtCore.QRect(280, 20, 121, 21))
        self.checkBox_20.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_13 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_13.setGeometry(QtCore.QRect(400, 110, 173, 27))
        self.checkBox_13.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_4.setGeometry(QtCore.QRect(0, 60, 181, 20))
        self.checkBox_4.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_10 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_10.setGeometry(QtCore.QRect(190, 40, 81, 27))
        self.checkBox_10.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 40, 151, 20))
        self.checkBox_2.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_14 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_14.setGeometry(QtCore.QRect(400, 40, 174, 27))
        self.checkBox_14.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_11 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_11.setGeometry(QtCore.QRect(190, 20, 68, 27))
        self.checkBox_11.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_8 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_8.setGeometry(QtCore.QRect(190, 60, 91, 27))
        self.checkBox_8.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_6.setGeometry(QtCore.QRect(0, 100, 151, 20))
        self.checkBox_6.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_16 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_16.setGeometry(QtCore.QRect(280, 80, 121, 27))
        self.checkBox_16.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_17.setGeometry(QtCore.QRect(280, 60, 131, 21))
        self.checkBox_17.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_7 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_7.setGeometry(QtCore.QRect(190, 80, 101, 27))
        self.checkBox_7.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_15 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_15.setGeometry(QtCore.QRect(400, 10, 156, 27))
        self.checkBox_15.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_12 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_12.setGeometry(QtCore.QRect(400, 60, 151, 27))
        self.checkBox_12.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_19 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_19.setGeometry(QtCore.QRect(280, 40, 111, 21))
        self.checkBox_19.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_9 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_9.setGeometry(QtCore.QRect(400, 80, 142, 27))
        self.checkBox_9.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_3.setGeometry(QtCore.QRect(0, 80, 181, 20))
        self.checkBox_3.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setGeometry(QtCore.QRect(0, 20, 101, 20))
        self.checkBox.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_5.setGeometry(QtCore.QRect(0, 120, 131, 20))
        self.checkBox_5.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_3 = QtWidgets.QLabel(menu)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(20, 570, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.listView_2 = QtWidgets.QListView(menu)
        self.listView_2.setGeometry(QtCore.QRect(600, 50, 641, 511))
        self.listView_2.setAutoFillBackground(False)
        self.listView_2.setStyleSheet("QListView{ border-image: url(srbtli.jpg);\n"
"image-opacity:0.5;\n"
"background-color :rgb(224, 255, 219);\n"
"color rgb(251, 255, 207);\n"
"}\n"
"")
        self.listView_2.setObjectName("listView_2")
        self.widget_5 = QtWidgets.QWidget(menu)
        self.widget_5.setGeometry(QtCore.QRect(610, 110, 581, 201))
        self.widget_5.setAutoFillBackground(False)
        self.widget_5.setStyleSheet("border-color: rgb(255, 247, 211);")
        self.widget_5.setObjectName("widget_5")
        self.checkBox_104 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_104.setGeometry(QtCore.QRect(10, 70, 197, 27))
        self.checkBox_104.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_104.setObjectName("checkBox_104")
        self.checkBox_105 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_105.setGeometry(QtCore.QRect(300, 20, 178, 27))
        self.checkBox_105.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_105.setObjectName("checkBox_105")
        self.checkBox_106 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_106.setGeometry(QtCore.QRect(10, 40, 184, 27))
        self.checkBox_106.setStyleSheet("\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_106.setObjectName("checkBox_106")
        self.checkBox_107 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_107.setGeometry(QtCore.QRect(300, 140, 97, 27))
        self.checkBox_107.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"color:white;\n"
"}")
        self.checkBox_107.setObjectName("checkBox_107")
        self.checkBox_108 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_108.setGeometry(QtCore.QRect(300, 50, 192, 27))
        self.checkBox_108.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_108.setObjectName("checkBox_108")
        self.checkBox_109 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_109.setGeometry(QtCore.QRect(10, 130, 151, 20))
        self.checkBox_109.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_109.setObjectName("checkBox_109")
        self.checkBox_110 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_110.setGeometry(QtCore.QRect(300, 80, 141, 27))
        self.checkBox_110.setStyleSheet("QCheckBox{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_110.setObjectName("checkBox_110")
        self.checkBox_111 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_111.setGeometry(QtCore.QRect(10, 100, 181, 20))
        self.checkBox_111.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_111.setObjectName("checkBox_111")
        self.checkBox_112 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_112.setGeometry(QtCore.QRect(10, 10, 184, 27))
        self.checkBox_112.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_112.setObjectName("checkBox_112")
        self.checkBox_113 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_113.setGeometry(QtCore.QRect(10, 160, 211, 27))
        self.checkBox_113.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_113.setObjectName("checkBox_113")
        self.checkBox_114 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_114.setGeometry(QtCore.QRect(300, 170, 171, 27))
        self.checkBox_114.setStyleSheet("QCheckBox{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_114.setObjectName("checkBox_114")
        self.checkBox_115 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_115.setGeometry(QtCore.QRect(300, 110, 191, 27))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_115.setFont(font)
        self.checkBox_115.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_115.setObjectName("checkBox_115")
        self.cmboxmagnolia_19 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxmagnolia_19.setGeometry(QtCore.QRect(220, 10, 71, 20))
        self.cmboxmagnolia_19.setObjectName("cmboxmagnolia_19")
        self.cmboxmagnolia_19.addItem("")
        self.cmboxmagnolia_19.addItem("")
        self.cmboxmagnolia_19.addItem("")
        self.cmboxmagnolia_19.addItem("")
        self.cmboxmagnolia_19.addItem("")
        self.cmboxirmik0 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik0.setGeometry(QtCore.QRect(220, 40, 71, 20))
        self.cmboxirmik0.setObjectName("cmboxirmik0")
        self.cmboxirmik0.addItem("")
        self.cmboxirmik0.addItem("")
        self.cmboxirmik0.addItem("")
        self.cmboxirmik0.addItem("")
        self.cmboxirmik0.addItem("")
        self.cmboxirmik1 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik1.setGeometry(QtCore.QRect(220, 70, 71, 20))
        self.cmboxirmik1.setObjectName("cmboxirmik1")
        self.cmboxirmik1.addItem("")
        self.cmboxirmik1.addItem("")
        self.cmboxirmik1.addItem("")
        self.cmboxirmik1.addItem("")
        self.cmboxirmik1.addItem("")
        self.cmboxirmik2 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik2.setGeometry(QtCore.QRect(220, 100, 71, 20))
        self.cmboxirmik2.setObjectName("cmboxirmik2")
        self.cmboxirmik2.addItem("")
        self.cmboxirmik2.addItem("")
        self.cmboxirmik2.addItem("")
        self.cmboxirmik2.addItem("")
        self.cmboxirmik2.addItem("")
        self.cmboxirmik3 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik3.setGeometry(QtCore.QRect(220, 130, 71, 20))
        self.cmboxirmik3.setObjectName("cmboxirmik3")
        self.cmboxirmik3.addItem("")
        self.cmboxirmik3.addItem("")
        self.cmboxirmik3.addItem("")
        self.cmboxirmik3.addItem("")
        self.cmboxirmik3.addItem("")
        self.cmboxirmik4 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik4.setGeometry(QtCore.QRect(220, 160, 71, 20))
        self.cmboxirmik4.setObjectName("cmboxirmik4")
        self.cmboxirmik4.addItem("")
        self.cmboxirmik4.addItem("")
        self.cmboxirmik4.addItem("")
        self.cmboxirmik4.addItem("")
        self.cmboxirmik4.addItem("")
        self.cmboxirmik5 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik5.setGeometry(QtCore.QRect(500, 20, 71, 20))
        self.cmboxirmik5.setObjectName("cmboxirmik5")
        self.cmboxirmik5.addItem("")
        self.cmboxirmik5.addItem("")
        self.cmboxirmik5.addItem("")
        self.cmboxirmik5.addItem("")
        self.cmboxirmik5.addItem("")
        self.cmboxirmik6 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik6.setGeometry(QtCore.QRect(500, 50, 71, 20))
        self.cmboxirmik6.setObjectName("cmboxirmik6")
        self.cmboxirmik6.addItem("")
        self.cmboxirmik6.addItem("")
        self.cmboxirmik6.addItem("")
        self.cmboxirmik6.addItem("")
        self.cmboxirmik6.addItem("")
        self.cmboxirmik7 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik7.setGeometry(QtCore.QRect(500, 80, 71, 20))
        self.cmboxirmik7.setObjectName("cmboxirmik7")
        self.cmboxirmik7.addItem("")
        self.cmboxirmik7.addItem("")
        self.cmboxirmik7.addItem("")
        self.cmboxirmik7.addItem("")
        self.cmboxirmik7.addItem("")
        self.cmboxirmik8 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik8.setGeometry(QtCore.QRect(500, 110, 71, 20))
        self.cmboxirmik8.setObjectName("cmboxirmik8")
        self.cmboxirmik8.addItem("")
        self.cmboxirmik8.addItem("")
        self.cmboxirmik8.addItem("")
        self.cmboxirmik8.addItem("")
        self.cmboxirmik8.addItem("")
        self.cmboxirmik9 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxirmik9.setGeometry(QtCore.QRect(500, 140, 71, 20))
        self.cmboxirmik9.setObjectName("cmboxirmik9")
        self.cmboxirmik9.addItem("")
        self.cmboxirmik9.addItem("")
        self.cmboxirmik9.addItem("")
        self.cmboxirmik9.addItem("")
        self.cmboxirmik9.addItem("")
        self.cmboxprofiterol0 = QtWidgets.Qcmboxmagnolia(self.widget_5)
        self.cmboxprofiterol0.setGeometry(QtCore.QRect(500, 170, 71, 20))
        self.cmboxprofiterol0.setObjectName("cmboxprofiterol0")
        self.cmboxprofiterol0.addItem("")
        self.cmboxprofiterol0.addItem("")
        self.cmboxprofiterol0.addItem("")
        self.cmboxprofiterol0.addItem("")
        self.cmboxprofiterol0.addItem("")
        self.label_6 = QtWidgets.QLabel(menu)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(630, 50, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background-color: rgb(219, 194, 165);\n"
"\n"
"font: 75 italic 25pt \"Palatino Linotype\";")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(menu)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(1040, 60, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(menu)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(0, 1020, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(menu)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(350, 570, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(menu)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(710, 590, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.listView_3 = QtWidgets.QListView(menu)
        self.listView_3.setGeometry(QtCore.QRect(600, 560, 641, 511))
        self.listView_3.setAutoFillBackground(False)
        self.listView_3.setStyleSheet("QListView{ \n"
"border-image: url(sevimlip.webp);\n"
"background-color :rgb(224, 255, 219);\n"
"color rgb(251, 255, 207);\n"
"}")
        self.listView_3.setObjectName("listView_3")
        self.label_9 = QtWidgets.QLabel(menu)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(1060, 570, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")
        self.widget_6 = QtWidgets.QWidget(menu)
        self.widget_6.setGeometry(QtCore.QRect(610, 610, 561, 187))
        self.widget_6.setAutoFillBackground(False)
        self.widget_6.setStyleSheet("border-color: rgb(255, 247, 211);")
        self.widget_6.setObjectName("widget_6")
        self.checkBox_128 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_128.setGeometry(QtCore.QRect(10, 60, 197, 27))
        self.checkBox_128.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_128.setObjectName("checkBox_128")
        self.checkBox_129 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_129.setGeometry(QtCore.QRect(350, 40, 196, 23))
        self.checkBox_129.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_129.setObjectName("checkBox_129")
        self.checkBox_130 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_130.setGeometry(QtCore.QRect(10, 30, 210, 23))
        self.checkBox_130.setStyleSheet("\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_130.setObjectName("checkBox_130")
        self.checkBox_131 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_131.setGeometry(QtCore.QRect(350, 10, 115, 23))
        self.checkBox_131.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"color:white;\n"
"}")
        self.checkBox_131.setObjectName("checkBox_131")
        self.checkBox_132 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_132.setGeometry(QtCore.QRect(350, 70, 192, 27))
        self.checkBox_132.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_132.setObjectName("checkBox_132")
        self.checkBox_133 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_133.setGeometry(QtCore.QRect(10, 130, 151, 20))
        self.checkBox_133.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_133.setObjectName("checkBox_133")
        self.checkBox_134 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_134.setGeometry(QtCore.QRect(350, 100, 148, 23))
        self.checkBox_134.setStyleSheet("QCheckBox{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_134.setObjectName("checkBox_134")
        self.checkBox_135 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_135.setGeometry(QtCore.QRect(10, 100, 181, 20))
        self.checkBox_135.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_135.setObjectName("checkBox_135")
        self.checkBox_136 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_136.setGeometry(QtCore.QRect(10, 0, 240, 23))
        self.checkBox_136.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_136.setObjectName("checkBox_136")
        self.checkBox_137 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_137.setGeometry(QtCore.QRect(10, 160, 215, 27))
        self.checkBox_137.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_137.setObjectName("checkBox_137")
        self.checkBox_139 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_139.setGeometry(QtCore.QRect(350, 130, 191, 27))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_139.setFont(font)
        self.checkBox_139.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_139.setObjectName("checkBox_139")
        self.cmboxmagnolia_7 = QtWidgets.Qcmboxmagnolia(self.widget_6)
        self.cmboxmagnolia_7.setGeometry(QtCore.QRect(260, 0, 71, 16))
        self.cmboxmagnolia_7.setObjectName("cmboxmagnolia_7")
        self.cmboxmagnolia_7.addItem("")
        self.cmboxmagnolia_7.addItem("")
        self.cmboxmagnolia_7.addItem("")
        self.cmboxmagnolia_7.addItem("")
        self.cmboxmagnolia_7.addItem("")
        self.cmboxmagnolia_8 = QtWidgets.Qcmboxmagnolia(self.widget_6)
        self.cmboxmagnolia_8.setGeometry(QtCore.QRect(260, 30, 71, 16))
        self.cmboxmagnolia_8.setObjectName("cmboxmagnolia_8")
        self.cmboxmagnolia_8.addItem("")
        self.cmboxmagnolia_8.addItem("")
        self.cmboxmagnolia_8.addItem("")
        self.cmboxmagnolia_8.addItem("")
        self.cmboxmagnolia_8.addItem("")
        self.cmboxmagnolia_9 = QtWidgets.Qcmboxmagnolia(self.widget_6)
        self.cmboxmagnolia_9.setGeometry(QtCore.QRect(260, 65, 71, 16))
        self.cmboxmagnolia_9.setObjectName("cmboxmagnolia_9")
        self.cmboxmagnolia_9.addItem("")
        self.cmboxmagnolia_9.addItem("")
        self.cmboxmagnolia_9.addItem("")
        self.cmboxmagnolia_9.addItem("")
        self.cmboxmagnolia_9.addItem("")
        self.cmboxmagnolia_10 = QtWidgets.Qcmboxmagnolia(self.widget_6)
        self.cmboxmagnolia_10.setGeometry(QtCore.QRect(260, 100, 71, 16))
        self.cmboxmagnolia_10.setObjectName("cmboxmagnolia_10")
        self.cmboxmagnolia_10.addItem("")
        self.cmboxmagnolia_10.addItem("")
        self.cmboxmagnolia_10.addItem("")
        self.cmboxmagnolia_10.addItem("")
        self.cmboxmagnolia_10.addItem("")
        self.cmboxmagnolia_11 = QtWidgets.Qcmboxmagnolia(self.widget_6)
        self.cmboxmagnolia_11.setGeometry(QtCore.QRect(260, 130, 71, 16))
        self.cmboxmagnolia_11.setObjectName("cmboxmagnolia_11")
        self.cmboxmagnolia_11.addItem("")
        self.cmboxmagnolia_11.addItem("")
        self.cmboxmagnolia_11.addItem("")
        self.cmboxmagnolia_11.addItem("")
        self.cmboxmagnolia_11.addItem("")
        self.cmboxmagnolia_12 = QtWidgets.Qcmboxmagnolia(self.widget_6)
        self.cmboxmagnolia_12.setGeometry(QtCore.QRect(260, 160, 71, 16))
        self.cmboxmagnolia_12.setObjectName("cmboxmagnolia_12")
        self.cmboxmagnolia_12.addItem("")
        self.cmboxmagnolia_12.addItem("")
        self.cmboxmagnolia_12.addItem("")
        self.cmboxmagnolia_12.addItem("")
        self.cmboxmagnolia_12.addItem("")
        self.label_11 = QtWidgets.QLabel(menu)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(730, 560, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 25pt \"Palatino Linotype\";")
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setObjectName("label_11")
        self.checkBox_138 = QtWidgets.QCheckBox(menu)
        self.checkBox_138.setGeometry(QtCore.QRect(940, 1010, 211, 23))
        self.checkBox_138.setStyleSheet("QCheckBox{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_138.setObjectName("checkBox_138")
        self.label_10 = QtWidgets.QLabel(menu)
        self.label_10.setGeometry(QtCore.QRect(1240, 50, 681, 1081))
        self.label_10.setStyleSheet(
"border-image: url(drink.jpg);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.checkBox_29 = QtWidgets.QCheckBox(menu)
        self.checkBox_29.setGeometry(QtCore.QRect(1270, 110, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_29.setFont(font)
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_33 = QtWidgets.QCheckBox(menu)
        self.checkBox_33.setGeometry(QtCore.QRect(1270, 310, 321, 27))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_33.setFont(font)
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(menu)
        self.checkBox_34.setGeometry(QtCore.QRect(1270, 190, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_34.setFont(font)
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_35 = QtWidgets.QCheckBox(menu)
        self.checkBox_35.setGeometry(QtCore.QRect(1270, 150, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_35.setFont(font)
        self.checkBox_35.setObjectName("checkBox_35")
        self.label_12 = QtWidgets.QLabel(menu)
        self.label_12.setEnabled(True)
        self.label_12.setGeometry(QtCore.QRect(1270, 50, 143, 58))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("\n"
"font: 75 italic 25pt \"Palatino Linotype\";")
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setObjectName("label_12")
        self.checkBox_36 = QtWidgets.QCheckBox(menu)
        self.checkBox_36.setGeometry(QtCore.QRect(1270, 230, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_36.setFont(font)
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(menu)
        self.checkBox_37.setGeometry(QtCore.QRect(1260, 420, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_37.setFont(font)
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(menu)
        self.checkBox_38.setGeometry(QtCore.QRect(1270, 270, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_38.setFont(font)
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_39 = QtWidgets.QCheckBox(menu)
        self.checkBox_39.setGeometry(QtCore.QRect(1260, 470, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_39.setFont(font)
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(menu)
        self.checkBox_40.setGeometry(QtCore.QRect(1260, 510, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_40.setFont(font)
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_41 = QtWidgets.QCheckBox(menu)
        self.checkBox_41.setGeometry(QtCore.QRect(1260, 550, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_41.setFont(font)
        self.checkBox_41.setObjectName("checkBox_41")
        self.cmboxmagnolia_6 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_6.setGeometry(QtCore.QRect(500, 580, 71, 31))
        self.cmboxmagnolia_6.setObjectName("cmboxmagnolia_6")
        self.cmboxmagnolia_6.addItem("")
        self.cmboxmagnolia_6.addItem("")
        self.cmboxmagnolia_6.addItem("")
        self.cmboxmagnolia_6.addItem("")
        self.cmboxmagnolia_6.addItem("")
        self.cmboxmagnolia_13 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_13.setGeometry(QtCore.QRect(1160, 620, 71, 20))
        self.cmboxmagnolia_13.setObjectName("cmboxmagnolia_13")
        self.cmboxmagnolia_13.addItem("")
        self.cmboxmagnolia_13.addItem("")
        self.cmboxmagnolia_13.addItem("")
        self.cmboxmagnolia_13.addItem("")
        self.cmboxmagnolia_13.addItem("")
        self.cmboxmagnolia_14 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_14.setGeometry(QtCore.QRect(1160, 650, 71, 20))
        self.cmboxmagnolia_14.setObjectName("cmboxmagnolia_14")
        self.cmboxmagnolia_14.addItem("")
        self.cmboxmagnolia_14.addItem("")
        self.cmboxmagnolia_14.addItem("")
        self.cmboxmagnolia_14.addItem("")
        self.cmboxmagnolia_14.addItem("")
        self.cmboxmagnolia_15 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_15.setGeometry(QtCore.QRect(1160, 680, 71, 20))
        self.cmboxmagnolia_15.setObjectName("cmboxmagnolia_15")
        self.cmboxmagnolia_15.addItem("")
        self.cmboxmagnolia_15.addItem("")
        self.cmboxmagnolia_15.addItem("")
        self.cmboxmagnolia_15.addItem("")
        self.cmboxmagnolia_15.addItem("")
        self.cmboxmagnolia_16 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_16.setGeometry(QtCore.QRect(1160, 710, 71, 20))
        self.cmboxmagnolia_16.setObjectName("cmboxmagnolia_16")
        self.cmboxmagnolia_16.addItem("")
        self.cmboxmagnolia_16.addItem("")
        self.cmboxmagnolia_16.addItem("")
        self.cmboxmagnolia_16.addItem("")
        self.cmboxmagnolia_16.addItem("")
        self.cmboxmagnolia_17 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_17.setGeometry(QtCore.QRect(1160, 740, 71, 20))
        self.cmboxmagnolia_17.setObjectName("cmboxmagnolia_17")
        self.cmboxmagnolia_17.addItem("")
        self.cmboxmagnolia_17.addItem("")
        self.cmboxmagnolia_17.addItem("")
        self.cmboxmagnolia_17.addItem("")
        self.cmboxmagnolia_17.addItem("")
        self.cmboxmagnolia_18 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_18.setGeometry(QtCore.QRect(1160, 1010, 71, 20))
        self.cmboxmagnolia_18.setObjectName("cmboxmagnolia_18")
        self.cmboxmagnolia_18.addItem("")
        self.cmboxmagnolia_18.addItem("")
        self.cmboxmagnolia_18.addItem("")
        self.cmboxmagnolia_18.addItem("")
        self.cmboxmagnolia_18.addItem("")
        self.cmboxprofiterol6 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxprofiterol6.setGeometry(QtCore.QRect(1380, 110, 71, 20))
        self.cmboxprofiterol6.setObjectName("cmboxprofiterol6")
        self.cmboxprofiterol6.addItem("")
        self.cmboxprofiterol6.addItem("")
        self.cmboxprofiterol6.addItem("")
        self.cmboxprofiterol6.addItem("")
        self.cmboxprofiterol6.addItem("")
        self.cmboxprofiterol7 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxprofiterol7.setGeometry(QtCore.QRect(1500, 150, 71, 20))
        self.cmboxprofiterol7.setObjectName("cmboxprofiterol7")
        self.cmboxprofiterol7.addItem("")
        self.cmboxprofiterol7.addItem("")
        self.cmboxprofiterol7.addItem("")
        self.cmboxprofiterol7.addItem("")
        self.cmboxprofiterol7.addItem("")
        self.cmboxprofiterol8 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxprofiterol8.setGeometry(QtCore.QRect(1500, 270, 71, 20))
        self.cmboxprofiterol8.setObjectName("cmboxprofiterol8")
        self.cmboxprofiterol8.addItem("")
        self.cmboxprofiterol8.addItem("")
        self.cmboxprofiterol8.addItem("")
        self.cmboxprofiterol8.addItem("")
        self.cmboxprofiterol8.addItem("")
        self.cmboxprofiterol9 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxprofiterol9.setGeometry(QtCore.QRect(1500, 230, 71, 20))
        self.cmboxprofiterol9.setObjectName("cmboxprofiterol9")
        self.cmboxprofiterol9.addItem("")
        self.cmboxprofiterol9.addItem("")
        self.cmboxprofiterol9.addItem("")
        self.cmboxprofiterol9.addItem("")
        self.cmboxprofiterol9.addItem("")
        self.cmboxmagnolia_40 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_40.setGeometry(QtCore.QRect(1500, 190, 71, 20))
        self.cmboxmagnolia_40.setObjectName("cmboxmagnolia_40")
        self.cmboxmagnolia_40.addItem("")
        self.cmboxmagnolia_40.addItem("")
        self.cmboxmagnolia_40.addItem("")
        self.cmboxmagnolia_40.addItem("")
        self.cmboxmagnolia_40.addItem("")
        self.cmboxmagnolia_41 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_41.setGeometry(QtCore.QRect(1530, 550, 71, 20))
        self.cmboxmagnolia_41.setObjectName("cmboxmagnolia_41")
        self.cmboxmagnolia_41.addItem("")
        self.cmboxmagnolia_41.addItem("")
        self.cmboxmagnolia_41.addItem("")
        self.cmboxmagnolia_41.addItem("")
        self.cmboxmagnolia_41.addItem("")
        self.cmboxmagnolia_42 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_42.setGeometry(QtCore.QRect(1460, 510, 71, 20))
        self.cmboxmagnolia_42.setObjectName("cmboxmagnolia_42")
        self.cmboxmagnolia_42.addItem("")
        self.cmboxmagnolia_42.addItem("")
        self.cmboxmagnolia_42.addItem("")
        self.cmboxmagnolia_42.addItem("")
        self.cmboxmagnolia_42.addItem("")
        self.cmboxmagnolia_43 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_43.setGeometry(QtCore.QRect(1460, 420, 71, 20))
        self.cmboxmagnolia_43.setObjectName("cmboxmagnolia_43")
        self.cmboxmagnolia_43.addItem("")
        self.cmboxmagnolia_43.addItem("")
        self.cmboxmagnolia_43.addItem("")
        self.cmboxmagnolia_43.addItem("")
        self.cmboxmagnolia_43.addItem("")
        self.cmboxmagnolia_44 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_44.setGeometry(QtCore.QRect(1590, 310, 71, 20))
        self.cmboxmagnolia_44.setObjectName("cmboxmagnolia_44")
        self.cmboxmagnolia_44.addItem("")
        self.cmboxmagnolia_44.addItem("")
        self.cmboxmagnolia_44.addItem("")
        self.cmboxmagnolia_44.addItem("")
        self.cmboxmagnolia_44.addItem("")
        self.cmboxmagnolia_45 = QtWidgets.Qcmboxmagnolia(menu)
        self.cmboxmagnolia_45.setGeometry(QtCore.QRect(1460, 470, 71, 20))
        self.cmboxmagnolia_45.setObjectName("cmboxmagnolia_45")
        self.cmboxmagnolia_45.addItem("")
        self.cmboxmagnolia_45.addItem("")
        self.cmboxmagnolia_45.addItem("")
        self.cmboxmagnolia_45.addItem("")
        self.cmboxmagnolia_45.addItem("")
        self.pushButton = QtWidgets.QPushButton(menu)
        self.pushButton.setGeometry(QtCore.QRect(1260, 850, 171, 51))
        self.pushButton.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"background-color:rgb(88, 25, 31);\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(115, 14, 18);")
        self.pushButton.setObjectName("pushButton")
        self.buttonBox = QtWidgets.QDialogButtonBox(menu)
        self.buttonBox.setGeometry(QtCore.QRect(1560, 900, 191, 51))
        self.buttonBox.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"background-color:rgb(88, 25, 31);\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(115, 14, 18);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_13 = QtWidgets.QLabel(menu)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 1921, 51))
        self.label_13.setStyleSheet("font: 75 italic 20pt \"Palatino Linotype\";\n"
"background-color: rgb(78, 52, 59);\n"
"color: rgb(245, 250, 246);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(menu)
        self.label_14.setGeometry(QtCore.QRect(1290, 900, 111, 41))
        self.label_14.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"background-color:rgb(88, 25, 31);\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(115, 14, 18);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(menu)
        self.label_15.setGeometry(QtCore.QRect(1560, 850, 191, 51))
        self.label_15.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"background-color:rgb(88, 25, 31);\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(115, 14, 18);")
        self.label_15.setObjectName("label_15")

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)



        self.checboxmagnolia.clicked.connect(lambda : self.fiyat(6))

        self.checkBoxsutlac.clicked.connect(lambda : self.fiyat(1))
        self.checkBoxTrilece.clicked.connect(lambda: self.fiyat(2))
        self.checkBoxgullac.clicked.connect(lambda: self.fiyat(3))
        self.checkboxmuhallebi.clicked.connect(lambda: self.fiyat(4))
        self.checkBoxkazandibi.clicked.connect(lambda: self.fiyat(5))
        self.checkBoxirmik.clicked.connect(lambda: self.fiyat(7))
        self.checkBoxprofiterol.clicked.connect(lambda: self.fiyat(8))
        self.checkBoxspungle.clicked.connect(lambda: self.fiyat(9))
        self.checkBoxkeskul.clicked.connect(lambda: self.fiyat(10))

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "Form"))
        self.checkBoxgullac.setText(_translate("menu", "Güllaç"))
        self.checkBoxirmik.setText(_translate("menu", "Sütlü irmik helvası"))
        self.label.setText(_translate("menu", "Sütlüler ☻"))
        self.checkBoxkazandibi.setText(_translate("menu", "Kazandibi"))
        self.checkBoxprofiterol.setText(_translate("menu", "Profiterol"))
        self.checkBoxspungle.setText(_translate("menu", "Spungle"))
        self.checboxmagnolia.setText(_translate("menu", "Magnolia"))
        self.checkboxmuhallebi.setText(_translate("menu", "Muhallebi"))
        self.checkBoxsutlac.setText(_translate("menu", "Fırında Sütlaç"))
        self.checkBoxTrilece.setText(_translate("menu", "Trileçe"))
        self.label_2.setText(_translate("menu", "Porsiyon: ₺ 20"))
        self.checkBoxkeskul.setText(_translate("menu", "Keşkül"))
        self.cmboxmagnolia.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik.setItemText(4, _translate("menu", "5"))
        self.cmboxprofiterol.setItemText(0, _translate("menu", "1"))
        self.cmboxprofiterol.setItemText(1, _translate("menu", "2"))
        self.cmboxprofiterol.setItemText(2, _translate("menu", "3"))
        self.cmboxprofiterol.setItemText(3, _translate("menu", "4"))
        self.cmboxprofiterol.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_4.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_4.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_4.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_4.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_4.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_5.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_5.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_5.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_5.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_5.setItemText(4, _translate("menu", "5"))
        self.cmboxsutlac.setItemText(0, _translate("menu", "1"))
        self.cmboxsutlac.setItemText(1, _translate("menu", "2"))
        self.cmboxsutlac.setItemText(2, _translate("menu", "3"))
        self.cmboxsutlac.setItemText(3, _translate("menu", "4"))
        self.cmboxsutlac.setItemText(4, _translate("menu", "5"))
        self.cmbBoxTrilece.setItemText(0, _translate("menu", "1"))
        self.cmbBoxTrilece.setItemText(1, _translate("menu", "2"))
        self.cmbBoxTrilece.setItemText(2, _translate("menu", "3"))
        self.cmbBoxTrilece.setItemText(3, _translate("menu", "4"))
        self.cmbBoxTrilece.setItemText(4, _translate("menu", "5"))
        self.cmbboxgullac.setItemText(0, _translate("menu", "1"))
        self.cmbboxgullac.setItemText(1, _translate("menu", "2"))
        self.cmbboxgullac.setItemText(2, _translate("menu", "3"))
        self.cmbboxgullac.setItemText(3, _translate("menu", "4"))
        self.cmbboxgullac.setItemText(4, _translate("menu", "5"))
        self.cmbboxmuhallebi.setItemText(0, _translate("menu", "1"))
        self.cmbboxmuhallebi.setItemText(1, _translate("menu", "2"))
        self.cmbboxmuhallebi.setItemText(2, _translate("menu", "3"))
        self.cmbboxmuhallebi.setItemText(3, _translate("menu", "4"))
        self.cmbboxmuhallebi.setItemText(4, _translate("menu", "5"))
        self.cmbboxkazandibi.setItemText(0, _translate("menu", "1"))
        self.cmbboxkazandibi.setItemText(1, _translate("menu", "2"))
        self.cmbboxkazandibi.setItemText(2, _translate("menu", "3"))
        self.cmbboxkazandibi.setItemText(3, _translate("menu", "4"))
        self.cmbboxkazandibi.setItemText(4, _translate("menu", "5"))
        self.checkBox_20.setText(_translate("menu", "fındık"))
        self.checkBox_13.setText(_translate("menu", "parça çikolata"))
        self.checkBox_4.setText(_translate("menu", "beyaz çikolata"))
        self.checkBox_10.setText(_translate("menu", "çilek"))
        self.checkBox_2.setText(_translate("menu", "fındık ezmesi"))
        self.checkBox_14.setText(_translate("menu", "portakal şekeri"))
        self.checkBox_11.setText(_translate("menu", "kivi"))
        self.checkBox_8.setText(_translate("menu", "muz"))
        self.checkBox_6.setText(_translate("menu", "Frambuaz"))
        self.checkBox_16.setText(_translate("menu", "bal"))
        self.checkBox_17.setText(_translate("menu", "h. cevizi"))
        self.checkBox_7.setText(_translate("menu", "vişne"))
        self.checkBox_15.setText(_translate("menu", "kırık kestane"))
        self.checkBox_12.setText(_translate("menu", "pudra şekeri"))
        self.checkBox_19.setText(_translate("menu", "ceviz"))
        self.checkBox_9.setText(_translate("menu", "renkli şeker"))
        self.checkBox_3.setText(_translate("menu", "bitter çikolata"))
        self.checkBox.setText(_translate("menu", "nutella"))
        self.checkBox_5.setText(_translate("menu", "dondurma(vanilya)"))
        self.label_3.setText(_translate("menu", "Waffle☻ "))
        self.checkBox_104.setText(_translate("menu", "Fındıklı Baklava"))
        self.checkBox_105.setText(_translate("menu", "Fıstıklı kadayıf"))
        self.checkBox_106.setText(_translate("menu", "Fıstıklı Baklava"))
        self.checkBox_107.setText(_translate("menu", "Künefe"))
        self.checkBox_108.setText(_translate("menu", "Kadayıf Dolması"))
        self.checkBox_109.setText(_translate("menu", "Şöbiyet"))
        self.checkBox_110.setText(_translate("menu", "Katmer"))
        self.checkBox_111.setText(_translate("menu", "Sütlü Nuriye"))
        self.checkBox_112.setText(_translate("menu", "Cevizli Baklava"))
        self.checkBox_113.setText(_translate("menu", "Çikolatalı Baklava"))
        self.checkBox_114.setText(_translate("menu", "Kaymak (+ ₺3)"))
        self.checkBox_115.setText(_translate("menu", "Ekmek Kadayıfı"))
        self.cmboxmagnolia_19.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_19.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_19.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_19.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_19.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik0.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik0.setItemText(1, _translate("menu", "2 "))
        self.cmboxirmik0.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik0.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik0.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik1.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik1.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik1.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik1.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik1.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik2.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik2.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik2.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik2.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik2.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik3.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik3.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik3.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik3.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik3.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik4.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik4.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik4.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik4.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik4.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik5.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik5.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik5.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik5.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik5.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik6.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik6.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik6.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik6.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik6.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik7.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik7.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik7.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik7.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik7.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik8.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik8.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik8.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik8.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik8.setItemText(4, _translate("menu", "5"))
        self.cmboxirmik9.setItemText(0, _translate("menu", "1"))
        self.cmboxirmik9.setItemText(1, _translate("menu", "2"))
        self.cmboxirmik9.setItemText(2, _translate("menu", "3"))
        self.cmboxirmik9.setItemText(3, _translate("menu", "4"))
        self.cmboxirmik9.setItemText(4, _translate("menu", "5"))
        self.cmboxprofiterol0.setItemText(0, _translate("menu", "1"))
        self.cmboxprofiterol0.setItemText(1, _translate("menu", "2"))
        self.cmboxprofiterol0.setItemText(2, _translate("menu", "3"))
        self.cmboxprofiterol0.setItemText(3, _translate("menu", "4"))
        self.cmboxprofiterol0.setItemText(4, _translate("menu", "5"))
        self.label_6.setText(_translate("menu", "  Şerbetliler ☻"))
        self.label_4.setText(_translate("menu", " Porsiyon: ₺ 25"))
        self.label_5.setText(_translate("menu", "Waffle alana çay ikramımızdır☻  "))
        self.label_7.setText(_translate("menu", "  Porsiyon: ₺ 25"))
        self.label_8.setText(_translate("menu", "Waffle☻ "))
        self.label_9.setText(_translate("menu", "  Porsiyon: ₺ 20"))
        self.checkBox_128.setText(_translate("menu", "Browni Cheescake"))
        self.checkBox_129.setText(_translate("menu", "Profiteröllü Pasta"))
        self.checkBox_130.setText(_translate("menu", "Limonlu Cheescake"))
        self.checkBox_131.setText(_translate("menu", "Tiramisu"))
        self.checkBox_132.setText(_translate("menu", "Fıstık Rüyası"))
        self.checkBox_133.setText(_translate("menu", "Mozaik Pasta"))
        self.checkBox_134.setText(_translate("menu", "Meyve Şöleni"))
        self.checkBox_135.setText(_translate("menu", "Browni"))
        self.checkBox_136.setText(_translate("menu", "Framboazlı Cheescake"))
        self.checkBox_137.setText(_translate("menu", "Kuruvasan"))
        self.checkBox_139.setText(_translate("menu", "Çikolatalım"))
        self.cmboxmagnolia_7.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_7.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_7.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_7.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_7.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_8.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_8.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_8.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_8.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_8.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_9.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_9.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_9.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_9.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_9.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_10.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_10.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_10.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_10.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_10.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_11.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_11.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_11.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_11.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_11.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_12.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_12.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_12.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_12.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_12.setItemText(4, _translate("menu", "5"))
        self.label_11.setText(_translate("menu", "Pastalar"))
        self.checkBox_138.setText(_translate("menu", "Özel Pasta  (₺ 60) "))
        self.checkBox_29.setText(_translate("menu", "Çay  ₺3"))
        self.checkBox_33.setText(_translate("menu", "Damla Sakızlı Türk Kahvesi"))
        self.checkBox_34.setText(_translate("menu", "Dibek Kahvesi  ₺15"))
        self.checkBox_35.setText(_translate("menu", "Türk Kahvesi  ₺12"))
        self.label_12.setText(_translate("menu", "İçecekler"))
        self.checkBox_36.setText(_translate("menu", "Sütlü Kahve  ₺15"))
        self.checkBox_37.setText(_translate("menu", "Maden Suyu  ₺4"))
        self.checkBox_38.setText(_translate("menu", "Sıcak Çikolata  ₺15"))
        self.checkBox_39.setText(_translate("menu", "Meyveli Soda  ₺5"))
        self.checkBox_40.setText(_translate("menu", "Ice Tea  ₺5"))
        self.checkBox_41.setText(_translate("menu", "Special Meyve Suyu  ₺15"))
        self.cmboxmagnolia_6.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_6.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_6.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_6.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_6.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_13.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_13.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_13.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_13.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_13.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_14.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_14.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_14.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_14.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_14.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_15.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_15.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_15.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_15.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_15.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_16.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_16.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_16.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_16.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_16.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_17.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_17.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_17.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_17.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_17.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_18.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_18.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_18.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_18.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_18.setItemText(4, _translate("menu", "5"))
        self.cmboxprofiterol6.setItemText(0, _translate("menu", "1"))
        self.cmboxprofiterol6.setItemText(1, _translate("menu", "2"))
        self.cmboxprofiterol6.setItemText(2, _translate("menu", "3"))
        self.cmboxprofiterol6.setItemText(3, _translate("menu", "4"))
        self.cmboxprofiterol6.setItemText(4, _translate("menu", "5"))
        self.cmboxprofiterol7.setItemText(0, _translate("menu", "1"))
        self.cmboxprofiterol7.setItemText(1, _translate("menu", "2"))
        self.cmboxprofiterol7.setItemText(2, _translate("menu", "3"))
        self.cmboxprofiterol7.setItemText(3, _translate("menu", "4"))
        self.cmboxprofiterol7.setItemText(4, _translate("menu", "5"))
        self.cmboxprofiterol8.setItemText(0, _translate("menu", "1"))
        self.cmboxprofiterol8.setItemText(1, _translate("menu", "2"))
        self.cmboxprofiterol8.setItemText(2, _translate("menu", "3"))
        self.cmboxprofiterol8.setItemText(3, _translate("menu", "4"))
        self.cmboxprofiterol8.setItemText(4, _translate("menu", "5 "))
        self.cmboxprofiterol9.setItemText(0, _translate("menu", "1"))
        self.cmboxprofiterol9.setItemText(1, _translate("menu", "2"))
        self.cmboxprofiterol9.setItemText(2, _translate("menu", "3"))
        self.cmboxprofiterol9.setItemText(3, _translate("menu", "4"))
        self.cmboxprofiterol9.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_40.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_40.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_40.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_40.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_40.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_41.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_41.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_41.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_41.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_41.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_42.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_42.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_42.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_42.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_42.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_43.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_43.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_43.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_43.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_43.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_44.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_44.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_44.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_44.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_44.setItemText(4, _translate("menu", "5"))
        self.cmboxmagnolia_45.setItemText(0, _translate("menu", "1"))
        self.cmboxmagnolia_45.setItemText(1, _translate("menu", "2"))
        self.cmboxmagnolia_45.setItemText(2, _translate("menu", "3"))
        self.cmboxmagnolia_45.setItemText(3, _translate("menu", "4"))
        self.cmboxmagnolia_45.setItemText(4, _translate("menu", "5"))
        self.pushButton.setText(_translate("menu", "TOPLAM FİYAT"))
        self.label_13.setText(_translate("menu", "                                                                                   ~~ TADIGÜZEL PASTANELERİ ~~"))
        self.label_14.setText(_translate("menu", " :"))
        self.label_15.setText(_translate("menu", " Siparişi Tamamla!"))

    def fiyat(self,id):
        price= self.getPriceSutluler(id)
        print(str(price))
        n=self.cmboxmagnolia.currentIndex() + 1
        total = price * n
        self.label_14.setText('%0.2f' % total)

    def getPriceSutluler(self,id):
        conn = sqlite3.connect('Our_data.db')
        curs = conn.cursor()
        content = 'select fiyat from Sutluler where sutluid= %d' % id
        res = curs.execute(content)
        for data in res:
            return   data[0]

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu = QtWidgets.QWidget()
    ui = Ui_menu()
    ui.setupUi(menu)
    menu.show()
    sys.exit(app.exec_())
