# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menupastane.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def a1(self):
        sutlac=40
        n=int(self.comboBox_31.text())
        total = sutlac * n
        self.label_14.setText('%0.2f' % total)





    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1919, 1070)
        Form.setStyleSheet("")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(0, 560, 601, 511))
        self.listView.setAutoFillBackground(False)
        self.listView.setStyleSheet("QListView{ \n"
"border-image: url(:/newPrefix/wfl1.jpg);\n"
"background-color :rgb(224, 255, 219);\n"
"color rgb(251, 255, 207);\n"
"}")
        self.listView.setObjectName("listView")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 50, 601, 511))
        self.frame.setStyleSheet("background-image: url(frnstlc.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.checkBox_23 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_23.setGeometry(QtCore.QRect(20, 110, 175, 27))
        self.checkBox_23.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_26 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_26.setGeometry(QtCore.QRect(310, 70, 221, 27))
        self.checkBox_26.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_26.setObjectName("checkBox_26")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 0, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBox_28 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_28.setGeometry(QtCore.QRect(20, 170, 175, 27))
        self.checkBox_28.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_25 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_25.setGeometry(QtCore.QRect(310, 100, 175, 27))
        self.checkBox_25.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_24 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_24.setGeometry(QtCore.QRect(310, 130, 175, 27))
        self.checkBox_24.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_18.setGeometry(QtCore.QRect(310, 40, 175, 27))
        self.checkBox_18.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_27 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_27.setGeometry(QtCore.QRect(20, 140, 175, 27))
        self.checkBox_27.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_21 = QtWidgets.QCheckBox(self.frame)

        self.checkBox_21.setGeometry(QtCore.QRect(20, 50, 175, 27))
        self.checkBox_21.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_21.clicked.connect(self.a1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_22.setGeometry(QtCore.QRect(20, 80, 175, 27))
        self.checkBox_22.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_22.setObjectName("checkBox_22")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(450, 10, 141, 21))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.checkBox_32 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_32.setGeometry(QtCore.QRect(310, 160, 175, 27))
        self.checkBox_32.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_32.setObjectName("checkBox_32")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(540, 40, 51, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(540, 70, 51, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(540, 100, 51, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setGeometry(QtCore.QRect(540, 130, 51, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.frame)
        self.comboBox_5.setGeometry(QtCore.QRect(540, 160, 51, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_31 = QtWidgets.QComboBox(self.frame)
        self.comboBox_31.setGeometry(QtCore.QRect(210, 50, 71, 20))
        self.comboBox_31.setObjectName("comboBox_31")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_32 = QtWidgets.QComboBox(self.frame)
        self.comboBox_32.setGeometry(QtCore.QRect(210, 80, 71, 20))
        self.comboBox_32.setObjectName("comboBox_32")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_33 = QtWidgets.QComboBox(self.frame)
        self.comboBox_33.setGeometry(QtCore.QRect(210, 110, 71, 20))
        self.comboBox_33.setObjectName("comboBox_33")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_34 = QtWidgets.QComboBox(self.frame)
        self.comboBox_34.setGeometry(QtCore.QRect(210, 140, 71, 20))
        self.comboBox_34.setObjectName("comboBox_34")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_35 = QtWidgets.QComboBox(self.frame)
        self.comboBox_35.setGeometry(QtCore.QRect(210, 170, 71, 20))
        self.comboBox_35.setObjectName("comboBox_35")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(0, 610, 601, 171))
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setObjectName("widget_2")
        self.checkBox_20 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_20.setGeometry(QtCore.QRect(280, 20, 121, 21))
        self.checkBox_20.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_13 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_13.setGeometry(QtCore.QRect(400, 110, 173, 27))
        self.checkBox_13.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_4.setGeometry(QtCore.QRect(0, 60, 181, 20))
        self.checkBox_4.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_10 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_10.setGeometry(QtCore.QRect(190, 40, 81, 27))
        self.checkBox_10.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 40, 151, 20))
        self.checkBox_2.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_14 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_14.setGeometry(QtCore.QRect(400, 40, 174, 27))
        self.checkBox_14.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_11 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_11.setGeometry(QtCore.QRect(190, 20, 68, 27))
        self.checkBox_11.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_8 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_8.setGeometry(QtCore.QRect(190, 60, 91, 27))
        self.checkBox_8.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_6.setGeometry(QtCore.QRect(0, 100, 151, 20))
        self.checkBox_6.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_16 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_16.setGeometry(QtCore.QRect(280, 80, 121, 27))
        self.checkBox_16.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_17.setGeometry(QtCore.QRect(280, 60, 131, 21))
        self.checkBox_17.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_7 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_7.setGeometry(QtCore.QRect(190, 80, 101, 27))
        self.checkBox_7.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_15 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_15.setGeometry(QtCore.QRect(400, 10, 156, 27))
        self.checkBox_15.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_12 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_12.setGeometry(QtCore.QRect(400, 60, 151, 27))
        self.checkBox_12.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_19 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_19.setGeometry(QtCore.QRect(280, 40, 111, 21))
        self.checkBox_19.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_9 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_9.setGeometry(QtCore.QRect(400, 80, 142, 27))
        self.checkBox_9.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_3.setGeometry(QtCore.QRect(0, 80, 181, 20))
        self.checkBox_3.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setGeometry(QtCore.QRect(0, 20, 101, 20))
        self.checkBox.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_5.setGeometry(QtCore.QRect(0, 120, 131, 20))
        self.checkBox_5.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(20, 570, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.listView_2 = QtWidgets.QListView(Form)
        self.listView_2.setGeometry(QtCore.QRect(600, 50, 641, 511))
        self.listView_2.setAutoFillBackground(False)
        self.listView_2.setStyleSheet("QListView{ border-image: url(:/newPrefix/srbtli.jpg);\n"
"image-opacity:0.5;\n"
"background-color :rgb(224, 255, 219);\n"
"color rgb(251, 255, 207);\n"
"}\n"
"")
        self.listView_2.setObjectName("listView_2")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setGeometry(QtCore.QRect(610, 110, 581, 201))
        self.widget_5.setAutoFillBackground(False)
        self.widget_5.setStyleSheet("border-color: rgb(255, 247, 211);")
        self.widget_5.setObjectName("widget_5")
        self.checkBox_104 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_104.setGeometry(QtCore.QRect(10, 70, 197, 27))
        self.checkBox_104.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_104.setObjectName("checkBox_104")
        self.checkBox_105 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_105.setGeometry(QtCore.QRect(300, 20, 178, 27))
        self.checkBox_105.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_105.setObjectName("checkBox_105")
        self.checkBox_106 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_106.setGeometry(QtCore.QRect(10, 40, 184, 27))
        self.checkBox_106.setStyleSheet("\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_106.setObjectName("checkBox_106")
        self.checkBox_107 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_107.setGeometry(QtCore.QRect(300, 140, 97, 27))
        self.checkBox_107.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"color:white;\n"
"}")
        self.checkBox_107.setObjectName("checkBox_107")
        self.checkBox_108 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_108.setGeometry(QtCore.QRect(300, 50, 192, 27))
        self.checkBox_108.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_108.setObjectName("checkBox_108")
        self.checkBox_109 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_109.setGeometry(QtCore.QRect(10, 130, 151, 20))
        self.checkBox_109.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_109.setObjectName("checkBox_109")
        self.checkBox_110 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_110.setGeometry(QtCore.QRect(300, 80, 141, 27))
        self.checkBox_110.setStyleSheet("QCheckBox{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_110.setObjectName("checkBox_110")
        self.checkBox_111 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_111.setGeometry(QtCore.QRect(10, 100, 181, 20))
        self.checkBox_111.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_111.setObjectName("checkBox_111")
        self.checkBox_112 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_112.setGeometry(QtCore.QRect(10, 10, 184, 27))
        self.checkBox_112.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_112.setObjectName("checkBox_112")
        self.checkBox_113 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_113.setGeometry(QtCore.QRect(10, 160, 211, 27))
        self.checkBox_113.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_113.setObjectName("checkBox_113")
        self.checkBox_114 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_114.setGeometry(QtCore.QRect(300, 170, 171, 27))
        self.checkBox_114.setStyleSheet("QCheckBox{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_114.setObjectName("checkBox_114")
        self.checkBox_115 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_115.setGeometry(QtCore.QRect(300, 110, 191, 27))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_115.setFont(font)
        self.checkBox_115.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_115.setObjectName("checkBox_115")
        self.comboBox_19 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_19.setGeometry(QtCore.QRect(220, 10, 71, 20))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_20 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_20.setGeometry(QtCore.QRect(220, 40, 71, 20))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_21 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_21.setGeometry(QtCore.QRect(220, 70, 71, 20))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_22 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_22.setGeometry(QtCore.QRect(220, 100, 71, 20))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_23 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_23.setGeometry(QtCore.QRect(220, 130, 71, 20))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_24 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_24.setGeometry(QtCore.QRect(220, 160, 71, 20))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_25 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_25.setGeometry(QtCore.QRect(500, 20, 71, 20))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_26 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_26.setGeometry(QtCore.QRect(500, 50, 71, 20))
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_27 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_27.setGeometry(QtCore.QRect(500, 80, 71, 20))
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_28 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_28.setGeometry(QtCore.QRect(500, 110, 71, 20))
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_29 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_29.setGeometry(QtCore.QRect(500, 140, 71, 20))
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_30 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_30.setGeometry(QtCore.QRect(500, 170, 71, 20))
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(630, 50, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background-color: rgb(219, 194, 165);\n"
"\n"
"font: 75 italic 25pt \"Palatino Linotype\";")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(1040, 60, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(0, 1020, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(350, 570, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(710, 590, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.listView_3 = QtWidgets.QListView(Form)
        self.listView_3.setGeometry(QtCore.QRect(600, 560, 641, 511))
        self.listView_3.setAutoFillBackground(False)
        self.listView_3.setStyleSheet("QListView{ \n"
"border-image: url(:/newPrefix/sevimlip.webp);\n"
"background-color :rgb(224, 255, 219);\n"
"color rgb(251, 255, 207);\n"
"}")
        self.listView_3.setObjectName("listView_3")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(1060, 570, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setGeometry(QtCore.QRect(610, 610, 561, 187))
        self.widget_6.setAutoFillBackground(False)
        self.widget_6.setStyleSheet("border-color: rgb(255, 247, 211);")
        self.widget_6.setObjectName("widget_6")
        self.checkBox_128 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_128.setGeometry(QtCore.QRect(10, 60, 197, 27))
        self.checkBox_128.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_128.setObjectName("checkBox_128")
        self.checkBox_129 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_129.setGeometry(QtCore.QRect(350, 40, 196, 23))
        self.checkBox_129.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_129.setObjectName("checkBox_129")
        self.checkBox_130 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_130.setGeometry(QtCore.QRect(10, 30, 210, 23))
        self.checkBox_130.setStyleSheet("\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_130.setObjectName("checkBox_130")
        self.checkBox_131 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_131.setGeometry(QtCore.QRect(350, 10, 115, 23))
        self.checkBox_131.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Lucida Handwriting\";\n"
"color:white;\n"
"}")
        self.checkBox_131.setObjectName("checkBox_131")
        self.checkBox_132 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_132.setGeometry(QtCore.QRect(350, 70, 192, 27))
        self.checkBox_132.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_132.setObjectName("checkBox_132")
        self.checkBox_133 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_133.setGeometry(QtCore.QRect(10, 130, 151, 20))
        self.checkBox_133.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_133.setObjectName("checkBox_133")
        self.checkBox_134 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_134.setGeometry(QtCore.QRect(350, 100, 148, 23))
        self.checkBox_134.setStyleSheet("QCheckBox{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_134.setObjectName("checkBox_134")
        self.checkBox_135 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_135.setGeometry(QtCore.QRect(10, 100, 181, 20))
        self.checkBox_135.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_135.setObjectName("checkBox_135")
        self.checkBox_136 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_136.setGeometry(QtCore.QRect(10, 0, 240, 23))
        self.checkBox_136.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_136.setObjectName("checkBox_136")
        self.checkBox_137 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_137.setGeometry(QtCore.QRect(10, 160, 215, 27))
        self.checkBox_137.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_137.setObjectName("checkBox_137")
        self.checkBox_139 = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox_139.setGeometry(QtCore.QRect(350, 130, 191, 27))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_139.setFont(font)
        self.checkBox_139.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_139.setObjectName("checkBox_139")
        self.comboBox_7 = QtWidgets.QComboBox(self.widget_6)
        self.comboBox_7.setGeometry(QtCore.QRect(260, 0, 71, 16))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.widget_6)
        self.comboBox_8.setGeometry(QtCore.QRect(260, 30, 71, 16))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(self.widget_6)
        self.comboBox_9.setGeometry(QtCore.QRect(260, 65, 71, 16))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(self.widget_6)
        self.comboBox_10.setGeometry(QtCore.QRect(260, 100, 71, 16))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_11 = QtWidgets.QComboBox(self.widget_6)
        self.comboBox_11.setGeometry(QtCore.QRect(260, 130, 71, 16))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(self.widget_6)
        self.comboBox_12.setGeometry(QtCore.QRect(260, 160, 71, 16))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(730, 560, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 25pt \"Palatino Linotype\";")
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setObjectName("label_11")
        self.checkBox_138 = QtWidgets.QCheckBox(Form)
        self.checkBox_138.setGeometry(QtCore.QRect(940, 1010, 211, 23))
        self.checkBox_138.setStyleSheet("QCheckBox{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 10pt \"Lucida Handwriting\";\n"
"}")
        self.checkBox_138.setObjectName("checkBox_138")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(1240, 50, 681, 1081))
        self.label_10.setStyleSheet("border-image: url(:/newPrefix/portakal.jpg);\n"
"border-image: url(:/newPrefix/drink.jpg);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.checkBox_29 = QtWidgets.QCheckBox(Form)
        self.checkBox_29.setGeometry(QtCore.QRect(1270, 110, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_29.setFont(font)
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_33 = QtWidgets.QCheckBox(Form)
        self.checkBox_33.setGeometry(QtCore.QRect(1270, 310, 321, 27))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_33.setFont(font)
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(Form)
        self.checkBox_34.setGeometry(QtCore.QRect(1270, 190, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_34.setFont(font)
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_35 = QtWidgets.QCheckBox(Form)
        self.checkBox_35.setGeometry(QtCore.QRect(1270, 150, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_35.setFont(font)
        self.checkBox_35.setObjectName("checkBox_35")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setEnabled(True)
        self.label_12.setGeometry(QtCore.QRect(1270, 50, 143, 58))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("\n"
"font: 75 italic 25pt \"Palatino Linotype\";")
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setObjectName("label_12")
        self.checkBox_36 = QtWidgets.QCheckBox(Form)
        self.checkBox_36.setGeometry(QtCore.QRect(1270, 230, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_36.setFont(font)
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(Form)
        self.checkBox_37.setGeometry(QtCore.QRect(1260, 420, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_37.setFont(font)
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(Form)
        self.checkBox_38.setGeometry(QtCore.QRect(1270, 270, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_38.setFont(font)
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_39 = QtWidgets.QCheckBox(Form)
        self.checkBox_39.setGeometry(QtCore.QRect(1260, 470, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_39.setFont(font)
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(Form)
        self.checkBox_40.setGeometry(QtCore.QRect(1260, 510, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_40.setFont(font)
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_41 = QtWidgets.QCheckBox(Form)
        self.checkBox_41.setGeometry(QtCore.QRect(1260, 550, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_41.setFont(font)
        self.checkBox_41.setObjectName("checkBox_41")
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setGeometry(QtCore.QRect(500, 580, 71, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_13 = QtWidgets.QComboBox(Form)
        self.comboBox_13.setGeometry(QtCore.QRect(1160, 620, 71, 20))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_14 = QtWidgets.QComboBox(Form)
        self.comboBox_14.setGeometry(QtCore.QRect(1160, 650, 71, 20))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_15 = QtWidgets.QComboBox(Form)
        self.comboBox_15.setGeometry(QtCore.QRect(1160, 680, 71, 20))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_16 = QtWidgets.QComboBox(Form)
        self.comboBox_16.setGeometry(QtCore.QRect(1160, 710, 71, 20))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_17 = QtWidgets.QComboBox(Form)
        self.comboBox_17.setGeometry(QtCore.QRect(1160, 740, 71, 20))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_18 = QtWidgets.QComboBox(Form)
        self.comboBox_18.setGeometry(QtCore.QRect(1160, 1010, 71, 20))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_36 = QtWidgets.QComboBox(Form)
        self.comboBox_36.setGeometry(QtCore.QRect(1380, 110, 71, 20))
        self.comboBox_36.setObjectName("comboBox_36")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_37 = QtWidgets.QComboBox(Form)
        self.comboBox_37.setGeometry(QtCore.QRect(1500, 150, 71, 20))
        self.comboBox_37.setObjectName("comboBox_37")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_38 = QtWidgets.QComboBox(Form)
        self.comboBox_38.setGeometry(QtCore.QRect(1500, 270, 71, 20))
        self.comboBox_38.setObjectName("comboBox_38")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_39 = QtWidgets.QComboBox(Form)
        self.comboBox_39.setGeometry(QtCore.QRect(1500, 230, 71, 20))
        self.comboBox_39.setObjectName("comboBox_39")
        self.comboBox_39.addItem("")
        self.comboBox_39.addItem("")
        self.comboBox_39.addItem("")
        self.comboBox_39.addItem("")
        self.comboBox_39.addItem("")
        self.comboBox_40 = QtWidgets.QComboBox(Form)
        self.comboBox_40.setGeometry(QtCore.QRect(1500, 190, 71, 20))
        self.comboBox_40.setObjectName("comboBox_40")
        self.comboBox_40.addItem("")
        self.comboBox_40.addItem("")
        self.comboBox_40.addItem("")
        self.comboBox_40.addItem("")
        self.comboBox_40.addItem("")
        self.comboBox_41 = QtWidgets.QComboBox(Form)
        self.comboBox_41.setGeometry(QtCore.QRect(1530, 550, 71, 20))
        self.comboBox_41.setObjectName("comboBox_41")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_42 = QtWidgets.QComboBox(Form)
        self.comboBox_42.setGeometry(QtCore.QRect(1460, 510, 71, 20))
        self.comboBox_42.setObjectName("comboBox_42")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_43 = QtWidgets.QComboBox(Form)
        self.comboBox_43.setGeometry(QtCore.QRect(1460, 420, 71, 20))
        self.comboBox_43.setObjectName("comboBox_43")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_44 = QtWidgets.QComboBox(Form)
        self.comboBox_44.setGeometry(QtCore.QRect(1590, 310, 71, 20))
        self.comboBox_44.setObjectName("comboBox_44")
        self.comboBox_44.addItem("")
        self.comboBox_44.addItem("")
        self.comboBox_44.addItem("")
        self.comboBox_44.addItem("")
        self.comboBox_44.addItem("")
        self.comboBox_45 = QtWidgets.QComboBox(Form)
        self.comboBox_45.setGeometry(QtCore.QRect(1460, 470, 71, 20))
        self.comboBox_45.setObjectName("comboBox_45")
        self.comboBox_45.addItem("")
        self.comboBox_45.addItem("")
        self.comboBox_45.addItem("")
        self.comboBox_45.addItem("")
        self.comboBox_45.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1260, 850, 171, 51))
        self.pushButton.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"background-color:rgb(88, 25, 31);\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(115, 14, 18);")
        self.pushButton.setObjectName("pushButton")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(1560, 900, 191, 51))
        self.buttonBox.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"background-color:rgb(88, 25, 31);\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(115, 14, 18);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 1921, 51))
        self.label_13.setStyleSheet("font: 75 italic 20pt \"Palatino Linotype\";\n"
"background-color: rgb(78, 52, 59);\n"
"color: rgb(245, 250, 246);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(1290, 900, 111, 41))
        self.label_14.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"background-color:rgb(88, 25, 31);\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(115, 14, 18);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(1560, 850, 191, 51))
        self.label_15.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"background-color:rgb(88, 25, 31);\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(115, 14, 18);")
        self.label_15.setObjectName("label_15")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_23.setText(_translate("Form", "Güllaç"))
        self.checkBox_26.setText(_translate("Form", "Sütlü irmik helvası"))
        self.label.setText(_translate("Form", "Sütlüler ☻"))
        self.checkBox_28.setText(_translate("Form", "Kazandibi"))
        self.checkBox_25.setText(_translate("Form", "Profiterol"))
        self.checkBox_24.setText(_translate("Form", "Spungle"))
        self.checkBox_18.setText(_translate("Form", "Magnolia"))
        self.checkBox_27.setText(_translate("Form", "Muhallebi"))
        self.checkBox_21.setText(_translate("Form", "Fırında Sütlaç"))
        self.checkBox_22.setText(_translate("Form", "Trileçe"))
        self.label_2.setText(_translate("Form", "Porsiyon: ₺ 20"))
        self.checkBox_32.setText(_translate("Form", "Keşkül"))
        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "2"))
        self.comboBox.setItemText(2, _translate("Form", "3"))
        self.comboBox.setItemText(3, _translate("Form", "4"))
        self.comboBox.setItemText(4, _translate("Form", "5"))
        self.comboBox_2.setItemText(0, _translate("Form", "1"))
        self.comboBox_2.setItemText(1, _translate("Form", "2"))
        self.comboBox_2.setItemText(2, _translate("Form", "3"))
        self.comboBox_2.setItemText(3, _translate("Form", "4"))
        self.comboBox_2.setItemText(4, _translate("Form", "5"))
        self.comboBox_3.setItemText(0, _translate("Form", "1"))
        self.comboBox_3.setItemText(1, _translate("Form", "2"))
        self.comboBox_3.setItemText(2, _translate("Form", "3"))
        self.comboBox_3.setItemText(3, _translate("Form", "4"))
        self.comboBox_3.setItemText(4, _translate("Form", "5"))
        self.comboBox_4.setItemText(0, _translate("Form", "1"))
        self.comboBox_4.setItemText(1, _translate("Form", "2"))
        self.comboBox_4.setItemText(2, _translate("Form", "3"))
        self.comboBox_4.setItemText(3, _translate("Form", "4"))
        self.comboBox_4.setItemText(4, _translate("Form", "5"))
        self.comboBox_5.setItemText(0, _translate("Form", "1"))
        self.comboBox_5.setItemText(1, _translate("Form", "2"))
        self.comboBox_5.setItemText(2, _translate("Form", "3"))
        self.comboBox_5.setItemText(3, _translate("Form", "4"))
        self.comboBox_5.setItemText(4, _translate("Form", "5"))
        self.comboBox_31.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_31.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_31.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_31.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_31.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_32.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_32.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_32.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_32.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_32.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_33.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_33.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_33.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_33.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_33.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_34.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_34.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_34.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_34.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_34.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_35.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_35.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_35.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_35.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_35.setItemText(4, _translate("Form", "5 adet"))
        self.checkBox_20.setText(_translate("Form", "fındık"))
        self.checkBox_13.setText(_translate("Form", "parça çikolata"))
        self.checkBox_4.setText(_translate("Form", "beyaz çikolata"))
        self.checkBox_10.setText(_translate("Form", "çilek"))
        self.checkBox_2.setText(_translate("Form", "fındık ezmesi"))
        self.checkBox_14.setText(_translate("Form", "portakal şekeri"))
        self.checkBox_11.setText(_translate("Form", "kivi"))
        self.checkBox_8.setText(_translate("Form", "muz"))
        self.checkBox_6.setText(_translate("Form", "Frambuaz"))
        self.checkBox_16.setText(_translate("Form", "bal"))
        self.checkBox_17.setText(_translate("Form", "h. cevizi"))
        self.checkBox_7.setText(_translate("Form", "vişne"))
        self.checkBox_15.setText(_translate("Form", "kırık kestane"))
        self.checkBox_12.setText(_translate("Form", "pudra şekeri"))
        self.checkBox_19.setText(_translate("Form", "ceviz"))
        self.checkBox_9.setText(_translate("Form", "renkli şeker"))
        self.checkBox_3.setText(_translate("Form", "bitter çikolata"))
        self.checkBox.setText(_translate("Form", "nutella"))
        self.checkBox_5.setText(_translate("Form", "dondurma(vanilya)"))
        self.label_3.setText(_translate("Form", "Waffle☻ "))
        self.checkBox_104.setText(_translate("Form", "Fındıklı Baklava"))
        self.checkBox_105.setText(_translate("Form", "Fıstıklı kadayıf"))
        self.checkBox_106.setText(_translate("Form", "Fıstıklı Baklava"))
        self.checkBox_107.setText(_translate("Form", "Künefe"))
        self.checkBox_108.setText(_translate("Form", "Kadayıf Dolması"))
        self.checkBox_109.setText(_translate("Form", "Şöbiyet"))
        self.checkBox_110.setText(_translate("Form", "Katmer"))
        self.checkBox_111.setText(_translate("Form", "Sütlü Nuriye"))
        self.checkBox_112.setText(_translate("Form", "Cevizli Baklava"))
        self.checkBox_113.setText(_translate("Form", "Çikolatalı Baklava"))
        self.checkBox_114.setText(_translate("Form", "Kaymak (+ ₺3)"))
        self.checkBox_115.setText(_translate("Form", "Ekmek Kadayıfı"))
        self.comboBox_19.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_19.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_19.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_19.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_19.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_20.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_20.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_20.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_20.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_20.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_21.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_21.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_21.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_21.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_21.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_22.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_22.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_22.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_22.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_22.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_23.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_23.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_23.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_23.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_23.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_24.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_24.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_24.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_24.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_24.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_25.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_25.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_25.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_25.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_25.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_26.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_26.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_26.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_26.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_26.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_27.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_27.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_27.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_27.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_27.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_28.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_28.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_28.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_28.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_28.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_29.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_29.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_29.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_29.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_29.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_30.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_30.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_30.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_30.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_30.setItemText(4, _translate("Form", "5 adet"))
        self.label_6.setText(_translate("Form", "  Şerbetliler ☻"))
        self.label_4.setText(_translate("Form", " Porsiyon: ₺ 25"))
        self.label_5.setText(_translate("Form", "Waffle alana çay ikramımızdır☻  "))
        self.label_7.setText(_translate("Form", "  Porsiyon: ₺ 25"))
        self.label_8.setText(_translate("Form", "Waffle☻ "))
        self.label_9.setText(_translate("Form", "  Porsiyon: ₺ 20"))
        self.checkBox_128.setText(_translate("Form", "Browni Cheescake"))
        self.checkBox_129.setText(_translate("Form", "Profiteröllü Pasta"))
        self.checkBox_130.setText(_translate("Form", "Limonlu Cheescake"))
        self.checkBox_131.setText(_translate("Form", "Tiramisu"))
        self.checkBox_132.setText(_translate("Form", "Fıstık Rüyası"))
        self.checkBox_133.setText(_translate("Form", "Mozaik Pasta"))
        self.checkBox_134.setText(_translate("Form", "Meyve Şöleni"))
        self.checkBox_135.setText(_translate("Form", "Browni"))
        self.checkBox_136.setText(_translate("Form", "Framboazlı Cheescake"))
        self.checkBox_137.setText(_translate("Form", "Kuruvasan"))
        self.checkBox_139.setText(_translate("Form", "Çikolatalım"))
        self.comboBox_7.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_7.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_7.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_7.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_7.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_8.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_8.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_8.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_8.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_8.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_9.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_9.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_9.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_9.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_9.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_10.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_10.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_10.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_10.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_10.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_11.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_11.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_11.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_11.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_11.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_12.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_12.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_12.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_12.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_12.setItemText(4, _translate("Form", "5 adet"))
        self.label_11.setText(_translate("Form", "Pastalar"))
        self.checkBox_138.setText(_translate("Form", "Özel Pasta  (₺ 60) "))
        self.checkBox_29.setText(_translate("Form", "Çay  ₺3"))
        self.checkBox_33.setText(_translate("Form", "Damla Sakızlı Türk Kahvesi"))
        self.checkBox_34.setText(_translate("Form", "Dibek Kahvesi  ₺15"))
        self.checkBox_35.setText(_translate("Form", "Türk Kahvesi  ₺12"))
        self.label_12.setText(_translate("Form", "İçecekler"))
        self.checkBox_36.setText(_translate("Form", "Sütlü Kahve  ₺15"))
        self.checkBox_37.setText(_translate("Form", "Maden Suyu  ₺4"))
        self.checkBox_38.setText(_translate("Form", "Sıcak Çikolata  ₺15"))
        self.checkBox_39.setText(_translate("Form", "Meyveli Soda  ₺5"))
        self.checkBox_40.setText(_translate("Form", "Ice Tea  ₺5"))
        self.checkBox_41.setText(_translate("Form", "Special Meyve Suyu  ₺15"))
        self.comboBox_6.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_6.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_6.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_6.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_6.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_13.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_13.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_13.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_13.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_13.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_14.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_14.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_14.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_14.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_14.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_15.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_15.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_15.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_15.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_15.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_16.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_16.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_16.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_16.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_16.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_17.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_17.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_17.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_17.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_17.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_18.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_18.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_18.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_18.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_18.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_36.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_36.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_36.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_36.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_36.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_37.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_37.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_37.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_37.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_37.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_38.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_38.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_38.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_38.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_38.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_39.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_39.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_39.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_39.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_39.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_40.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_40.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_40.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_40.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_40.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_41.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_41.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_41.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_41.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_41.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_42.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_42.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_42.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_42.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_42.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_43.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_43.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_43.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_43.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_43.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_44.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_44.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_44.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_44.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_44.setItemText(4, _translate("Form", "5 adet"))
        self.comboBox_45.setItemText(0, _translate("Form", "1 adet"))
        self.comboBox_45.setItemText(1, _translate("Form", "2 adet"))
        self.comboBox_45.setItemText(2, _translate("Form", "3 adet"))
        self.comboBox_45.setItemText(3, _translate("Form", "4 adet"))
        self.comboBox_45.setItemText(4, _translate("Form", "5 adet"))
        self.pushButton.setText(_translate("Form", "TOPLAM FİYAT"))
        self.label_13.setText(_translate("Form", "                                                                                     ~~ TADIGÜZEL PASTANELERİ ~~"))
        self.label_14.setText(_translate("Form", " :"))
        self.label_15.setText(_translate("Form", " Siparişi Tamamla!"))
#import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
