from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(1708, 1468)
        menu.setStyleSheet("")
        self.frame = QtWidgets.QFrame(menu)
        self.frame.setGeometry(QtCore.QRect(0, 50, 601, 511))
        self.frame.setStyleSheet("background-image: url(frnstlc.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.checkBoxgullac = QtWidgets.QCheckBox(self.frame)
        self.checkBoxgullac.setGeometry(QtCore.QRect(20, 110, 175, 27))
        self.checkBoxgullac.setStyleSheet("QCheckBox{\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxgullac.setObjectName("checkBoxgullac")
        self.checkBoxirmik = QtWidgets.QCheckBox(self.frame)
        self.checkBoxirmik.setGeometry(QtCore.QRect(310, 70, 221, 27))
        self.checkBoxirmik.setStyleSheet("QCheckBox{\n"
                                         "font: 10pt \"Lucida Handwriting\";\n"
                                         "}")
        self.checkBoxirmik.setObjectName("checkBoxirmik")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 0, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBoxkazandibi = QtWidgets.QCheckBox(self.frame)
        self.checkBoxkazandibi.setGeometry(QtCore.QRect(20, 170, 175, 27))
        self.checkBoxkazandibi.setStyleSheet("QCheckBox{\n"
                                             "font: 10pt \"Lucida Handwriting\";\n"
                                             "}")
        self.checkBoxkazandibi.setObjectName("checkBoxkazandibi")
        self.checkBoxprof = QtWidgets.QCheckBox(self.frame)
        self.checkBoxprof.setGeometry(QtCore.QRect(310, 100, 175, 27))
        self.checkBoxprof.setStyleSheet("QCheckBox{\n"
                                        "font: 10pt \"Lucida Handwriting\";\n"
                                        "}")
        self.checkBoxprof.setObjectName("checkBoxprof")
        self.checkBoxspungle = QtWidgets.QCheckBox(self.frame)
        self.checkBoxspungle.setGeometry(QtCore.QRect(310, 130, 175, 27))
        self.checkBoxspungle.setStyleSheet("QCheckBox{\n"
                                           "font: 10pt \"Lucida Handwriting\";\n"
                                           "}")
        self.checkBoxspungle.setObjectName("checkBoxspungle")
        self.checkBoxmagnolia = QtWidgets.QCheckBox(self.frame)
        self.checkBoxmagnolia.setGeometry(QtCore.QRect(310, 40, 175, 27))
        self.checkBoxmagnolia.setStyleSheet("QCheckBox{\n"
                                            "font: 10pt \"Lucida Handwriting\";\n"
                                            "}")
        self.checkBoxmagnolia.setObjectName("checkBoxmagnolia")
        self.checkBoxmuhallebi = QtWidgets.QCheckBox(self.frame)
        self.checkBoxmuhallebi.setGeometry(QtCore.QRect(20, 140, 175, 27))
        self.checkBoxmuhallebi.setStyleSheet("QCheckBox{\n"
                                             "font: 10pt \"Lucida Handwriting\";\n"
                                             "}")
        self.checkBoxmuhallebi.setObjectName("checkBoxmuhallebi")
        self.checkBoxsutlac = QtWidgets.QCheckBox(self.frame)
        self.checkBoxsutlac.setGeometry(QtCore.QRect(20, 50, 175, 27))
        self.checkBoxsutlac.setStyleSheet("QCheckBox{\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxsutlac.setObjectName("checkBoxsutlac")
        self.checkBoxtrilece = QtWidgets.QCheckBox(self.frame)
        self.checkBoxtrilece.setGeometry(QtCore.QRect(20, 80, 175, 27))
        self.checkBoxtrilece.setStyleSheet("QCheckBox{\n"
                                           "font: 10pt \"Lucida Handwriting\";\n"
                                           "}")
        self.checkBoxtrilece.setObjectName("checkBoxtrilece")
        self.label_sutluler = QtWidgets.QLabel(self.frame)
        self.label_sutluler.setGeometry(QtCore.QRect(450, 10, 141, 21))
        self.label_sutluler.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_sutluler.setObjectName("label_sutluler")
        self.checkBoxkeskul = QtWidgets.QCheckBox(self.frame)
        self.checkBoxkeskul.setGeometry(QtCore.QRect(310, 160, 175, 27))
        self.checkBoxkeskul.setStyleSheet("QCheckBox{\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxkeskul.setObjectName("checkBoxkeskul")
        self.comboBoxmagnolia = QtWidgets.QComboBox(self.frame)
        self.comboBoxmagnolia.setGeometry(QtCore.QRect(540, 40, 51, 22))
        self.comboBoxmagnolia.setObjectName("comboBoxmagnolia")
        self.comboBoxmagnolia.addItem("")
        self.comboBoxmagnolia.addItem("")
        self.comboBoxmagnolia.addItem("")
        self.comboBoxmagnolia.addItem("")
        self.comboBoxmagnolia.addItem("")
        self.comboBoxirmik = QtWidgets.QComboBox(self.frame)
        self.comboBoxirmik.setGeometry(QtCore.QRect(540, 70, 51, 22))
        self.comboBoxirmik.setObjectName("comboBoxirmik")
        self.comboBoxirmik.addItem("")
        self.comboBoxirmik.addItem("")
        self.comboBoxirmik.addItem("")
        self.comboBoxirmik.addItem("")
        self.comboBoxirmik.addItem("")
        self.comboBoxprof = QtWidgets.QComboBox(self.frame)
        self.comboBoxprof.setGeometry(QtCore.QRect(540, 100, 51, 22))
        self.comboBoxprof.setObjectName("comboBoxprof")
        self.comboBoxprof.addItem("")
        self.comboBoxprof.addItem("")
        self.comboBoxprof.addItem("")
        self.comboBoxprof.addItem("")
        self.comboBoxprof.addItem("")
        self.comboBoxspungle = QtWidgets.QComboBox(self.frame)
        self.comboBoxspungle.setGeometry(QtCore.QRect(540, 130, 51, 22))
        self.comboBoxspungle.setObjectName("comboBoxspungle")
        self.comboBoxspungle.addItem("")
        self.comboBoxspungle.addItem("")
        self.comboBoxspungle.addItem("")
        self.comboBoxspungle.addItem("")
        self.comboBoxspungle.addItem("")
        self.comboBoxkeskul = QtWidgets.QComboBox(self.frame)
        self.comboBoxkeskul.setGeometry(QtCore.QRect(540, 160, 51, 22))
        self.comboBoxkeskul.setObjectName("comboBoxkeskul")
        self.comboBoxkeskul.addItem("")
        self.comboBoxkeskul.addItem("")
        self.comboBoxkeskul.addItem("")
        self.comboBoxkeskul.addItem("")
        self.comboBoxkeskul.addItem("")
        self.comboBoxsutlac = QtWidgets.QComboBox(self.frame)
        self.comboBoxsutlac.setGeometry(QtCore.QRect(210, 50, 71, 20))
        self.comboBoxsutlac.setObjectName("comboBoxsutlac")
        self.comboBoxsutlac.addItem("")
        self.comboBoxsutlac.addItem("")
        self.comboBoxsutlac.addItem("")
        self.comboBoxsutlac.addItem("")
        self.comboBoxsutlac.addItem("")
        self.comboBoxtrilece = QtWidgets.QComboBox(self.frame)
        self.comboBoxtrilece.setGeometry(QtCore.QRect(210, 80, 71, 20))
        self.comboBoxtrilece.setObjectName("comboBoxtrilece")
        self.comboBoxtrilece.addItem("")
        self.comboBoxtrilece.addItem("")
        self.comboBoxtrilece.addItem("")
        self.comboBoxtrilece.addItem("")
        self.comboBoxtrilece.addItem("")
        self.comboBoxgullac = QtWidgets.QComboBox(self.frame)
        self.comboBoxgullac.setGeometry(QtCore.QRect(210, 110, 71, 20))
        self.comboBoxgullac.setObjectName("comboBoxgullac")
        self.comboBoxgullac.addItem("")
        self.comboBoxgullac.addItem("")
        self.comboBoxgullac.addItem("")
        self.comboBoxgullac.addItem("")
        self.comboBoxgullac.addItem("")
        self.comboBoxmuhallebi = QtWidgets.QComboBox(self.frame)
        self.comboBoxmuhallebi.setGeometry(QtCore.QRect(210, 140, 71, 20))
        self.comboBoxmuhallebi.setObjectName("comboBoxmuhallebi")
        self.comboBoxmuhallebi.addItem("")
        self.comboBoxmuhallebi.addItem("")
        self.comboBoxmuhallebi.addItem("")
        self.comboBoxmuhallebi.addItem("")
        self.comboBoxmuhallebi.addItem("")
        self.comboBoxkazandibi = QtWidgets.QComboBox(self.frame)
        self.comboBoxkazandibi.setGeometry(QtCore.QRect(210, 170, 71, 20))
        self.comboBoxkazandibi.setObjectName("comboBoxkazandibi")
        self.comboBoxkazandibi.addItem("")
        self.comboBoxkazandibi.addItem("")
        self.comboBoxkazandibi.addItem("")
        self.comboBoxkazandibi.addItem("")
        self.comboBoxkazandibi.addItem("")
        self.checkBoxgullac.raise_()
        self.checkBoxirmik.raise_()
        self.label.raise_()
        self.checkBoxkazandibi.raise_()
        self.checkBoxprof.raise_()
        self.checkBoxspungle.raise_()
        self.checkBoxmagnolia.raise_()
        self.checkBoxmuhallebi.raise_()
        self.checkBoxsutlac.raise_()
        self.checkBoxtrilece.raise_()
        self.label_sutluler.raise_()
        self.checkBoxkeskul.raise_()
        self.comboBoxmagnolia.raise_()
        self.comboBoxirmik.raise_()
        self.comboBoxprof.raise_()
        self.comboBoxspungle.raise_()
        self.comboBoxkeskul.raise_()
        self.comboBoxsutlac.raise_()
        self.comboBoxtrilece.raise_()
        self.comboBoxgullac.raise_()
        self.comboBoxmuhallebi.raise_()
        self.comboBoxkazandibi.raise_()
        self.label_2 = QtWidgets.QLabel(menu)
        self.label_2.setGeometry(QtCore.QRect(600, 59, 638, 501))
        self.label_2.setStyleSheet("QLabel{ border-image: url(srbtli.jpg);\n"
                                   "image-opacity:0.5;\n"
                                   "\n"
                                   "color rgb(251, 255, 207);\n"
                                   "}\n"
                                   "")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(menu)
        self.label_4.setGeometry(QtCore.QRect(0, 560, 631, 501))
        self.label_4.setStyleSheet("QLabel{ \n"
                                   "border-image: url(wfl1.jpg);\n"
                                   "\n"
                                   "color rgb(251, 255, 207);\n"
                                   "}")
        self.widget_2 = QtWidgets.QWidget(menu)
        self.widget_2.setGeometry(QtCore.QRect(0, 620, 601, 171))
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setObjectName("widget_2")
        self.checkBoxfindik = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxfindik.setGeometry(QtCore.QRect(280, 20, 121, 21))
        self.checkBoxfindik.setStyleSheet("QCheckBox{\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxfindik.setObjectName("checkBoxfindik")
        self.checkBoxbeyazcikolata = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxbeyazcikolata.setGeometry(QtCore.QRect(0, 60, 181, 20))
        self.checkBoxbeyazcikolata.setStyleSheet("QCheckBox{\n"
                                                 "font: 10pt \"Lucida Handwriting\";\n"
                                                 "}")
        self.checkBoxbeyazcikolata.setObjectName("checkBoxbeyazcikolata")
        self.checkBoxcilek = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxcilek.setGeometry(QtCore.QRect(190, 40, 81, 27))
        self.checkBoxcilek.setStyleSheet("QCheckBox{\n"
                                         "font: 10pt \"Lucida Handwriting\";\n"
                                         "}")
        self.checkBoxcilek.setObjectName("checkBoxcilek")
        self.checkBoxfndkezmesi = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxfndkezmesi.setGeometry(QtCore.QRect(0, 40, 151, 20))
        self.checkBoxfndkezmesi.setStyleSheet("QCheckBox{\n"
                                              "font: 10pt \"Lucida Handwriting\";\n"
                                              "}")
        self.checkBoxfndkezmesi.setObjectName("checkBoxfndkezmesi")
        self.checkBoxkivi = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxkivi.setGeometry(QtCore.QRect(190, 20, 68, 27))
        self.checkBoxkivi.setStyleSheet("QCheckBox{\n"
                                        "font: 10pt \"Lucida Handwriting\";\n"
                                        "}")
        self.checkBoxkivi.setObjectName("checkBoxkivi")
        self.checkBoxmuz = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxmuz.setGeometry(QtCore.QRect(190, 60, 91, 27))
        self.checkBoxmuz.setStyleSheet("QCheckBox{\n"
                                       "font: 10pt \"Lucida Handwriting\";\n"
                                       "}")
        self.checkBoxmuz.setObjectName("checkBoxmuz")
        self.checkBoxframbuaz = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxframbuaz.setGeometry(QtCore.QRect(0, 100, 151, 20))
        self.checkBoxframbuaz.setStyleSheet("QCheckBox{\n"
                                            "font: 10pt \"Lucida Handwriting\";\n"
                                            "}")
        self.checkBoxframbuaz.setObjectName("checkBoxframbuaz")
        self.checkBoxbal = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxbal.setGeometry(QtCore.QRect(280, 80, 121, 27))
        self.checkBoxbal.setStyleSheet("QCheckBox{\n"
                                       "font: 10pt \"Lucida Handwriting\";\n"
                                       "}")
        self.checkBoxbal.setObjectName("checkBoxbal")
        self.checkBoxhindistan = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxhindistan.setGeometry(QtCore.QRect(280, 60, 131, 21))
        self.checkBoxhindistan.setStyleSheet("QCheckBox{\n"
                                             "font: 10pt \"Lucida Handwriting\";\n"
                                             "}")
        self.checkBoxhindistan.setObjectName("checkBoxhindistan")
        self.checkBoxvisne = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxvisne.setGeometry(QtCore.QRect(190, 80, 101, 27))
        self.checkBoxvisne.setStyleSheet("QCheckBox{\n"
                                         "font: 10pt \"Lucida Handwriting\";\n"
                                         "}")
        self.checkBoxvisne.setObjectName("checkBoxvisne")
        self.checkBoxceviz = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxceviz.setGeometry(QtCore.QRect(280, 40, 111, 21))
        self.checkBoxceviz.setStyleSheet("QCheckBox{\n"
                                         "font: 10pt \"Lucida Handwriting\";\n"
                                         "}")
        self.checkBoxceviz.setObjectName("checkBoxceviz")
        self.checkBoxbittercik = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxbittercik.setGeometry(QtCore.QRect(0, 80, 181, 20))
        self.checkBoxbittercik.setStyleSheet("QCheckBox{\n"
                                             "font: 10pt \"Lucida Handwriting\";\n"
                                             "}")
        self.checkBoxbittercik.setObjectName("checkBoxbittercik")
        self.checkBoxnutella = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxnutella.setGeometry(QtCore.QRect(0, 20, 101, 20))
        self.checkBoxnutella.setStyleSheet("QCheckBox{\n"
                                           "font: 10pt \"Lucida Handwriting\";\n"
                                           "}")
        self.checkBoxnutella.setObjectName("checkBoxnutella")
        self.checkBoxdondurma = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxdondurma.setGeometry(QtCore.QRect(0, 120, 171, 20))
        self.checkBoxdondurma.setStyleSheet("QCheckBox{\n"
                                            "font: 10pt \"Lucida Handwriting\";\n"
                                            "}")
        self.checkBoxdondurma.setObjectName("checkBoxdondurma")
        self.checkBoxfindik.raise_()
        self.checkBoxbeyazcikolata.raise_()
        self.checkBoxcilek.raise_()
        self.checkBoxfndkezmesi.raise_()
        self.checkBoxkivi.raise_()
        self.checkBoxmuz.raise_()
        self.checkBoxframbuaz.raise_()
        self.checkBoxbal.raise_()
        self.checkBoxhindistan.raise_()
        self.checkBoxvisne.raise_()
        self.checkBoxceviz.raise_()
        self.checkBoxbittercik.raise_()
        self.checkBoxnutella.raise_()
        self.checkBoxdondurma.raise_()
        self.label_3 = QtWidgets.QLabel(menu)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(20, 580, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.widget_5 = QtWidgets.QWidget(menu)
        self.widget_5.setGeometry(QtCore.QRect(610, 110, 581, 201))
        self.widget_5.setAutoFillBackground(False)
        self.widget_5.setStyleSheet("border-color: rgb(255, 247, 211);")
        self.widget_5.setObjectName("widget_5")
        self.checkBoxfindikli = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxfindikli.setGeometry(QtCore.QRect(10, 70, 197, 27))
        self.checkBoxfindikli.setStyleSheet("QCheckBox{\n"
                                            "    color: rgb(255, 255, 255);\n"
                                            "font: 10pt \"Lucida Handwriting\";\n"
                                            "}")
        self.checkBoxfindikli.setObjectName("checkBoxfindikli")
        self.checkBoxfkadayif = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxfkadayif.setGeometry(QtCore.QRect(300, 20, 178, 27))
        self.checkBoxfkadayif.setStyleSheet("QCheckBox{\n"
                                            "    color: rgb(255, 255, 255);\n"
                                            "font: 10pt \"Lucida Handwriting\";\n"
                                            "}")
        self.checkBoxfkadayif.setObjectName("checkBoxfkadayif")
        self.checkBoxfistikli = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxfistikli.setGeometry(QtCore.QRect(10, 40, 184, 27))
        self.checkBoxfistikli.setStyleSheet("\n"
                                            "QCheckBox{\n"
                                            "    color: rgb(255, 255, 255);\n"
                                            "font: 10pt \"Lucida Handwriting\";\n"
                                            "}")
        self.checkBoxfistikli.setObjectName("checkBoxfistikli")
        self.checkBoxkunefe = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxkunefe.setGeometry(QtCore.QRect(300, 140, 97, 27))
        self.checkBoxkunefe.setStyleSheet("QCheckBox{\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "color:white;\n"
                                          "}")
        self.checkBoxkunefe.setObjectName("checkBoxkunefe")
        self.checkBoxkdolma = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxkdolma.setGeometry(QtCore.QRect(300, 50, 192, 27))
        self.checkBoxkdolma.setStyleSheet("QCheckBox{\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxkdolma.setObjectName("checkBoxkdolma")
        self.checkBoxsobiyet = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxsobiyet.setGeometry(QtCore.QRect(10, 130, 151, 20))
        self.checkBoxsobiyet.setStyleSheet("QCheckBox{\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "font: 10pt \"Lucida Handwriting\";\n"
                                           "}")
        self.checkBoxsobiyet.setObjectName("checkBoxsobiyet")
        self.checkBoxkatmer = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxkatmer.setGeometry(QtCore.QRect(300, 80, 141, 27))
        self.checkBoxkatmer.setStyleSheet("QCheckBox{\n"
                                          "    font: 75 8pt \"MS Shell Dlg 2\";\n"
                                          "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    font: 75 8pt \"MS Shell Dlg 2\";\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxkatmer.setObjectName("checkBoxkatmer")
        self.checkBoxnuriye = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxnuriye.setGeometry(QtCore.QRect(10, 100, 181, 20))
        self.checkBoxnuriye.setStyleSheet("QCheckBox{\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxnuriye.setObjectName("checkBoxnuriye")
        self.checkBoxcevizli = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxcevizli.setGeometry(QtCore.QRect(10, 10, 184, 27))
        self.checkBoxcevizli.setStyleSheet("QCheckBox{\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "font: 10pt \"Lucida Handwriting\";\n"
                                           "}")
        self.checkBoxcevizli.setObjectName("checkBoxcevizli")
        self.checkBoxcikobak = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxcikobak.setGeometry(QtCore.QRect(10, 160, 211, 27))
        self.checkBoxcikobak.setStyleSheet("QCheckBox{\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "font: 10pt \"Lucida Handwriting\";\n"
                                           "}")
        self.checkBoxcikobak.setObjectName("checkBoxcikobak")
        self.checkBoxkaymak = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxkaymak.setGeometry(QtCore.QRect(300, 170, 171, 27))
        self.checkBoxkaymak.setStyleSheet("QCheckBox{\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxkaymak.setObjectName("checkBoxkaymak")
        self.checkBoxekmek = QtWidgets.QCheckBox(self.widget_5)
        self.checkBoxekmek.setGeometry(QtCore.QRect(300, 110, 191, 27))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBoxekmek.setFont(font)
        self.checkBoxekmek.setStyleSheet("QCheckBox{\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "font: 10pt \"Lucida Handwriting\";\n"
                                         "}")
        self.checkBoxekmek.setObjectName("checkBoxekmek")
        self.comboBoxcevizli = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxcevizli.setGeometry(QtCore.QRect(220, 10, 71, 20))
        self.comboBoxcevizli.setObjectName("comboBoxcevizli")
        self.comboBoxcevizli.addItem("")
        self.comboBoxcevizli.addItem("")
        self.comboBoxcevizli.addItem("")
        self.comboBoxcevizli.addItem("")
        self.comboBoxcevizli.addItem("")
        self.comboBoxfistikli = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxfistikli.setGeometry(QtCore.QRect(220, 40, 71, 20))
        self.comboBoxfistikli.setObjectName("comboBoxfistikli")
        self.comboBoxfistikli.addItem("")
        self.comboBoxfistikli.addItem("")
        self.comboBoxfistikli.addItem("")
        self.comboBoxfistikli.addItem("")
        self.comboBoxfistikli.addItem("")
        self.comboBoxfindikli = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxfindikli.setGeometry(QtCore.QRect(220, 70, 71, 20))
        self.comboBoxfindikli.setObjectName("comboBoxfindikli")
        self.comboBoxfindikli.addItem("")
        self.comboBoxfindikli.addItem("")
        self.comboBoxfindikli.addItem("")
        self.comboBoxfindikli.addItem("")
        self.comboBoxfindikli.addItem("")
        self.comboBoxnuriye = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxnuriye.setGeometry(QtCore.QRect(220, 100, 71, 20))
        self.comboBoxnuriye.setObjectName("comboBoxnuriye")
        self.comboBoxnuriye.addItem("")
        self.comboBoxnuriye.addItem("")
        self.comboBoxnuriye.addItem("")
        self.comboBoxnuriye.addItem("")
        self.comboBoxnuriye.addItem("")
        self.comboBoxsobiyet = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxsobiyet.setGeometry(QtCore.QRect(220, 130, 71, 20))
        self.comboBoxsobiyet.setObjectName("comboBoxsobiyet")
        self.comboBoxsobiyet.addItem("")
        self.comboBoxsobiyet.addItem("")
        self.comboBoxsobiyet.addItem("")
        self.comboBoxsobiyet.addItem("")
        self.comboBoxsobiyet.addItem("")
        self.comboBoxcikobak = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxcikobak.setGeometry(QtCore.QRect(220, 160, 71, 20))
        self.comboBoxcikobak.setObjectName("comboBoxcikobak")
        self.comboBoxcikobak.addItem("")
        self.comboBoxcikobak.addItem("")
        self.comboBoxcikobak.addItem("")
        self.comboBoxcikobak.addItem("")
        self.comboBoxcikobak.addItem("")
        self.comboBoxfkadayif = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxfkadayif.setGeometry(QtCore.QRect(500, 20, 71, 20))
        self.comboBoxfkadayif.setObjectName("comboBoxfkadayif")
        self.comboBoxfkadayif.addItem("")
        self.comboBoxfkadayif.addItem("")
        self.comboBoxfkadayif.addItem("")
        self.comboBoxfkadayif.addItem("")
        self.comboBoxfkadayif.addItem("")
        self.comboBoxkdolma = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxkdolma.setGeometry(QtCore.QRect(500, 50, 71, 20))
        self.comboBoxkdolma.setObjectName("comboBoxkdolma")
        self.comboBoxkdolma.addItem("")
        self.comboBoxkdolma.addItem("")
        self.comboBoxkdolma.addItem("")
        self.comboBoxkdolma.addItem("")
        self.comboBoxkdolma.addItem("")
        self.comboBoxkatmer = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxkatmer.setGeometry(QtCore.QRect(500, 80, 71, 20))
        self.comboBoxkatmer.setObjectName("comboBoxkatmer")
        self.comboBoxkatmer.addItem("")
        self.comboBoxkatmer.addItem("")
        self.comboBoxkatmer.addItem("")
        self.comboBoxkatmer.addItem("")
        self.comboBoxkatmer.addItem("")
        self.comboBoxekmek = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxekmek.setGeometry(QtCore.QRect(500, 110, 71, 20))
        self.comboBoxekmek.setObjectName("comboBoxekmek")
        self.comboBoxekmek.addItem("")
        self.comboBoxekmek.addItem("")
        self.comboBoxekmek.addItem("")
        self.comboBoxekmek.addItem("")
        self.comboBoxekmek.addItem("")
        self.comboBoxkunefe = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxkunefe.setGeometry(QtCore.QRect(500, 140, 71, 20))
        self.comboBoxkunefe.setObjectName("comboBoxkunefe")
        self.comboBoxkunefe.addItem("")
        self.comboBoxkunefe.addItem("")
        self.comboBoxkunefe.addItem("")
        self.comboBoxkunefe.addItem("")
        self.comboBoxkunefe.addItem("")
        self.comboBoxkaymak = QtWidgets.QComboBox(self.widget_5)
        self.comboBoxkaymak.setGeometry(QtCore.QRect(500, 170, 71, 20))
        self.comboBoxkaymak.setObjectName("comboBoxkaymak")
        self.comboBoxkaymak.addItem("")
        self.comboBoxkaymak.addItem("")
        self.comboBoxkaymak.addItem("")
        self.comboBoxkaymak.addItem("")
        self.comboBoxkaymak.addItem("")
        self.label_6 = QtWidgets.QLabel(menu)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(630, 50, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background-color: rgb(219, 194, 165);\n"
                                   "\n"
                                   "font: 75 italic 25pt \"Palatino Linotype\";")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.label_serbetliler = QtWidgets.QLabel(menu)
        self.label_serbetliler.setEnabled(True)
        self.label_serbetliler.setGeometry(QtCore.QRect(1040, 60, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_serbetliler.setFont(font)
        self.label_serbetliler.setAutoFillBackground(False)
        self.label_serbetliler.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                             "")
        self.label_serbetliler.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_serbetliler.setObjectName("label_serbetliler")
        self.label_5 = QtWidgets.QLabel(menu)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(20, 1020, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.label_waffle = QtWidgets.QLabel(menu)
        self.label_waffle.setEnabled(True)
        self.label_waffle.setGeometry(QtCore.QRect(350, 580, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_waffle.setFont(font)
        self.label_waffle.setAutoFillBackground(False)
        self.label_waffle.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_waffle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_waffle.setObjectName("label_waffle")
        self.label_8 = QtWidgets.QLabel(menu)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(710, 590, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.listView_3 = QtWidgets.QListView(menu)
        self.listView_3.setGeometry(QtCore.QRect(600, 560, 641, 511))
        self.listView_3.setAutoFillBackground(False)
        self.listView_3.setStyleSheet("QListView{ \n"
                                      "border-image: url(sevimlip.webp);\n"
                                      "background-color :rgb(224, 255, 219);\n"
                                      "color rgb(251, 255, 207);\n"
                                      "}")
        self.listView_3.setObjectName("listView_3")
        self.label_pastalar = QtWidgets.QLabel(menu)
        self.label_pastalar.setEnabled(True)
        self.label_pastalar.setGeometry(QtCore.QRect(1060, 570, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_pastalar.setFont(font)
        self.label_pastalar.setAutoFillBackground(False)
        self.label_pastalar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_pastalar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_pastalar.setObjectName("label_pastalar")
        self.widget_6 = QtWidgets.QWidget(menu)
        self.widget_6.setGeometry(QtCore.QRect(600, 610, 631, 187))
        self.widget_6.setAutoFillBackground(False)
        self.widget_6.setStyleSheet("border-color: rgb(255, 247, 211);")
        self.widget_6.setObjectName("widget_6")
        self.checkBoxlcake = QtWidgets.QCheckBox(self.widget_6)
        self.checkBoxlcake.setGeometry(QtCore.QRect(10, 30, 210, 23))
        self.checkBoxlcake.setStyleSheet("\n"
                                         "QCheckBox{\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "font: 10pt \"Lucida Handwriting\";\n"
                                         "}")
        self.checkBoxlcake.setObjectName("checkBoxlcake")
        self.checkBoxtiramisu = QtWidgets.QCheckBox(self.widget_6)
        self.checkBoxtiramisu.setGeometry(QtCore.QRect(350, 10, 115, 23))
        self.checkBoxtiramisu.setStyleSheet("QCheckBox{\n"
                                            "font: 10pt \"Lucida Handwriting\";\n"
                                            "color:white;\n"
                                            "}")
        self.checkBoxtiramisu.setObjectName("checkBoxtiramisu")
        self.checkBoxfistikryasi = QtWidgets.QCheckBox(self.widget_6)
        self.checkBoxfistikryasi.setGeometry(QtCore.QRect(350, 50, 192, 27))
        self.checkBoxfistikryasi.setStyleSheet("QCheckBox{\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "font: 10pt \"Lucida Handwriting\";\n"
                                               "}")
        self.checkBoxfistikryasi.setObjectName("checkBoxfistikryasi")
        self.checkBoxmozaik = QtWidgets.QCheckBox(self.widget_6)
        self.checkBoxmozaik.setGeometry(QtCore.QRect(10, 100, 151, 20))
        self.checkBoxmozaik.setStyleSheet("QCheckBox{\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxmozaik.setObjectName("checkBoxmozaik")
        self.checkBoxmeyvesoleni = QtWidgets.QCheckBox(self.widget_6)
        self.checkBoxmeyvesoleni.setGeometry(QtCore.QRect(350, 90, 148, 23))
        self.checkBoxmeyvesoleni.setStyleSheet("QCheckBox{\n"
                                               "    font: 75 8pt \"MS Shell Dlg 2\";\n"
                                               "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "    font: 75 8pt \"MS Shell Dlg 2\";\n"
                                               "font: 10pt \"Lucida Handwriting\";\n"
                                               "}")
        self.checkBoxmeyvesoleni.setObjectName("checkBoxmeyvesoleni")
        self.checkBoxbrowni = QtWidgets.QCheckBox(self.widget_6)
        self.checkBoxbrowni.setGeometry(QtCore.QRect(10, 70, 181, 20))
        self.checkBoxbrowni.setStyleSheet("QCheckBox{\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "font: 10pt \"Lucida Handwriting\";\n"
                                          "}")
        self.checkBoxbrowni.setObjectName("checkBoxbrowni")
        self.checkBoxfcake = QtWidgets.QCheckBox(self.widget_6)
        self.checkBoxfcake.setGeometry(QtCore.QRect(10, 0, 240, 23))
        self.checkBoxfcake.setStyleSheet("QCheckBox{\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "font: 10pt \"Lucida Handwriting\";\n"
                                         "}")
        self.checkBoxfcake.setObjectName("checkBoxfcake")
        self.checkBoxkuruvasan = QtWidgets.QCheckBox(self.widget_6)
        self.checkBoxkuruvasan.setGeometry(QtCore.QRect(10, 130, 215, 27))
        self.checkBoxkuruvasan.setStyleSheet("QCheckBox{\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "font: 10pt \"Lucida Handwriting\";\n"
                                             "}")
        self.checkBoxkuruvasan.setObjectName("checkBoxkuruvasan")
        self.checkBoxcikolatalim = QtWidgets.QCheckBox(self.widget_6)
        self.checkBoxcikolatalim.setGeometry(QtCore.QRect(350, 120, 191, 27))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBoxcikolatalim.setFont(font)
        self.checkBoxcikolatalim.setStyleSheet("QCheckBox{\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "font: 10pt \"Lucida Handwriting\";\n"
                                               "}")
        self.checkBoxcikolatalim.setObjectName("checkBoxcikolatalim")
        self.comboBoxfcake = QtWidgets.QComboBox(self.widget_6)
        self.comboBoxfcake.setGeometry(QtCore.QRect(260, 0, 71, 16))
        self.comboBoxfcake.setObjectName("comboBoxfcake")
        self.comboBoxfcake.addItem("")
        self.comboBoxfcake.addItem("")
        self.comboBoxfcake.addItem("")
        self.comboBoxfcake.addItem("")
        self.comboBoxfcake.addItem("")
        self.comboBoxlcake = QtWidgets.QComboBox(self.widget_6)
        self.comboBoxlcake.setGeometry(QtCore.QRect(260, 30, 71, 16))
        self.comboBoxlcake.setObjectName("comboBoxlcake")
        self.comboBoxlcake.addItem("")
        self.comboBoxlcake.addItem("")
        self.comboBoxlcake.addItem("")
        self.comboBoxlcake.addItem("")
        self.comboBoxlcake.addItem("")
        self.comboBoxbrowni = QtWidgets.QComboBox(self.widget_6)
        self.comboBoxbrowni.setGeometry(QtCore.QRect(260, 70, 71, 16))
        self.comboBoxbrowni.setObjectName("comboBoxbrowni")
        self.comboBoxbrowni.addItem("")
        self.comboBoxbrowni.addItem("")
        self.comboBoxbrowni.addItem("")
        self.comboBoxbrowni.addItem("")
        self.comboBoxbrowni.addItem("")
        self.comboBoxmozaik = QtWidgets.QComboBox(self.widget_6)
        self.comboBoxmozaik.setGeometry(QtCore.QRect(260, 100, 71, 16))
        self.comboBoxmozaik.setObjectName("comboBoxmozaik")
        self.comboBoxmozaik.addItem("")
        self.comboBoxmozaik.addItem("")
        self.comboBoxmozaik.addItem("")
        self.comboBoxmozaik.addItem("")
        self.comboBoxmozaik.addItem("")
        self.comboBoxkuruvasan = QtWidgets.QComboBox(self.widget_6)
        self.comboBoxkuruvasan.setGeometry(QtCore.QRect(260, 130, 71, 16))
        self.comboBoxkuruvasan.setObjectName("comboBoxkuruvasan")
        self.comboBoxkuruvasan.addItem("")
        self.comboBoxkuruvasan.addItem("")
        self.comboBoxkuruvasan.addItem("")
        self.comboBoxkuruvasan.addItem("")
        self.comboBoxkuruvasan.addItem("")
        self.comboBoxmeyvesoleni = QtWidgets.QComboBox(self.widget_6)
        self.comboBoxmeyvesoleni.setGeometry(QtCore.QRect(560, 90, 71, 20))
        self.comboBoxmeyvesoleni.setObjectName("comboBoxmeyvesoleni")
        self.comboBoxmeyvesoleni.addItem("")
        self.comboBoxmeyvesoleni.addItem("")
        self.comboBoxmeyvesoleni.addItem("")
        self.comboBoxmeyvesoleni.addItem("")
        self.comboBoxmeyvesoleni.addItem("")
        self.comboBoxcikolatalim = QtWidgets.QComboBox(self.widget_6)
        self.comboBoxcikolatalim.setGeometry(QtCore.QRect(560, 120, 71, 20))
        self.comboBoxcikolatalim.setObjectName("comboBoxcikolatalim")
        self.comboBoxcikolatalim.addItem("")
        self.comboBoxcikolatalim.addItem("")
        self.comboBoxcikolatalim.addItem("")
        self.comboBoxcikolatalim.addItem("")
        self.comboBoxcikolatalim.addItem("")
        self.label_11 = QtWidgets.QLabel(menu)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(730, 560, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "font: 75 italic 25pt \"Palatino Linotype\";")
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setObjectName("label_11")
        self.checkBoxozelpasta = QtWidgets.QCheckBox(menu)
        self.checkBoxozelpasta.setGeometry(QtCore.QRect(940, 1010, 211, 23))
        self.checkBoxozelpasta.setStyleSheet("QCheckBox{\n"
                                             "color: rgb(255, 255, 255);\n"
                                             "\n"
                                             "font: 10pt \"Lucida Handwriting\";\n"
                                             "}")
        self.checkBoxozelpasta.setObjectName("checkBoxozelpasta")
        self.label_10 = QtWidgets.QLabel(menu)
        self.label_10.setGeometry(QtCore.QRect(1240, 50, 681, 1081))
        self.label_10.setStyleSheet("border-image: url(portakal.jpg);\n"
                                    "border-image: url(drink.jpg);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.checkBoxcay = QtWidgets.QCheckBox(menu)
        self.checkBoxcay.setGeometry(QtCore.QRect(1270, 110, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBoxcay.setFont(font)
        self.checkBoxcay.setObjectName("checkBoxcay")
        self.checkBoxdamlasakizli = QtWidgets.QCheckBox(menu)
        self.checkBoxdamlasakizli.setGeometry(QtCore.QRect(1270, 310, 321, 27))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBoxdamlasakizli.setFont(font)
        self.checkBoxdamlasakizli.setObjectName("checkBoxdamlasakizli")
        self.checkBoxdibek = QtWidgets.QCheckBox(menu)
        self.checkBoxdibek.setGeometry(QtCore.QRect(1270, 190, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBoxdibek.setFont(font)
        self.checkBoxdibek.setObjectName("checkBoxdibek")
        self.checkBoxturkkahvesi = QtWidgets.QCheckBox(menu)
        self.checkBoxturkkahvesi.setGeometry(QtCore.QRect(1270, 150, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBoxturkkahvesi.setFont(font)
        self.checkBoxturkkahvesi.setObjectName("checkBoxturkkahvesi")
        self.label_12 = QtWidgets.QLabel(menu)
        self.label_12.setEnabled(True)
        self.label_12.setGeometry(QtCore.QRect(1270, 50, 143, 58))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("\n"
                                    "font: 75 italic 25pt \"Palatino Linotype\";")
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setObjectName("label_12")
        self.checkBoxsutlukahve = QtWidgets.QCheckBox(menu)
        self.checkBoxsutlukahve.setGeometry(QtCore.QRect(1270, 230, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBoxsutlukahve.setFont(font)
        self.checkBoxsutlukahve.setObjectName("checkBoxsutlukahve")
        self.checkBoxmadensuyu = QtWidgets.QCheckBox(menu)
        self.checkBoxmadensuyu.setGeometry(QtCore.QRect(1260, 420, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBoxmadensuyu.setFont(font)
        self.checkBoxmadensuyu.setObjectName("checkBoxmadensuyu")
        self.checkBox_38 = QtWidgets.QCheckBox(menu)
        self.checkBox_38.setGeometry(QtCore.QRect(1270, 270, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBox_38.setFont(font)
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBoxmeyvelisoda = QtWidgets.QCheckBox(menu)
        self.checkBoxmeyvelisoda.setGeometry(QtCore.QRect(1260, 470, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBoxmeyvelisoda.setFont(font)
        self.checkBoxmeyvelisoda.setObjectName("checkBoxmeyvelisoda")
        self.checkBoxicetea = QtWidgets.QCheckBox(menu)
        self.checkBoxicetea.setGeometry(QtCore.QRect(1260, 510, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBoxicetea.setFont(font)
        self.checkBoxicetea.setObjectName("checkBoxicetea")
        self.checkBoxspecial = QtWidgets.QCheckBox(menu)
        self.checkBoxspecial.setGeometry(QtCore.QRect(1260, 550, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.checkBoxspecial.setFont(font)
        self.checkBoxspecial.setObjectName("checkBoxspecial")
        self.comboBox_waffle = QtWidgets.QComboBox(menu)
        self.comboBox_waffle.setGeometry(QtCore.QRect(500, 590, 71, 31))
        self.comboBox_waffle.setObjectName("comboBox_waffle")
        self.comboBox_waffle.addItem("")
        self.comboBox_waffle.addItem("")
        self.comboBox_waffle.addItem("")
        self.comboBox_waffle.addItem("")
        self.comboBox_waffle.addItem("")
        self.comboBoxtiramisu = QtWidgets.QComboBox(menu)
        self.comboBoxtiramisu.setGeometry(QtCore.QRect(1160, 620, 71, 20))
        self.comboBoxtiramisu.setObjectName("comboBoxtiramisu")
        self.comboBoxtiramisu.addItem("")
        self.comboBoxtiramisu.addItem("")
        self.comboBoxtiramisu.addItem("")
        self.comboBoxtiramisu.addItem("")
        self.comboBoxtiramisu.addItem("")
        self.comboBoxfistikruyasi = QtWidgets.QComboBox(menu)
        self.comboBoxfistikruyasi.setGeometry(QtCore.QRect(1160, 660, 71, 20))
        self.comboBoxfistikruyasi.setObjectName("comboBoxfistikruyasi")
        self.comboBoxfistikruyasi.addItem("")
        self.comboBoxfistikruyasi.addItem("")
        self.comboBoxfistikruyasi.addItem("")
        self.comboBoxfistikruyasi.addItem("")
        self.comboBoxfistikruyasi.addItem("")
        self.comboBoxozelpasta = QtWidgets.QComboBox(menu)
        self.comboBoxozelpasta.setGeometry(QtCore.QRect(1160, 1010, 71, 20))
        self.comboBoxozelpasta.setObjectName("comboBoxozelpasta")
        self.comboBoxozelpasta.addItem("")
        self.comboBoxozelpasta.addItem("")
        self.comboBoxozelpasta.addItem("")
        self.comboBoxozelpasta.addItem("")
        self.comboBoxozelpasta.addItem("")
        self.comboBoxcay = QtWidgets.QComboBox(menu)
        self.comboBoxcay.setGeometry(QtCore.QRect(1380, 110, 71, 20))
        self.comboBoxcay.setObjectName("comboBoxcay")
        self.comboBoxcay.addItem("")
        self.comboBoxcay.addItem("")
        self.comboBoxcay.addItem("")
        self.comboBoxcay.addItem("")
        self.comboBoxcay.addItem("")
        self.comboBoxturkkahvesi = QtWidgets.QComboBox(menu)
        self.comboBoxturkkahvesi.setGeometry(QtCore.QRect(1500, 150, 71, 20))
        self.comboBoxturkkahvesi.setObjectName("comboBoxturkkahvesi")
        self.comboBoxturkkahvesi.addItem("")
        self.comboBoxturkkahvesi.addItem("")
        self.comboBoxturkkahvesi.addItem("")
        self.comboBoxturkkahvesi.addItem("")
        self.comboBoxturkkahvesi.addItem("")
        self.comboBox_38 = QtWidgets.QComboBox(menu)
        self.comboBox_38.setGeometry(QtCore.QRect(1500, 270, 71, 20))
        self.comboBox_38.setObjectName("comboBox_38")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBoxsutlukahve = QtWidgets.QComboBox(menu)
        self.comboBoxsutlukahve.setGeometry(QtCore.QRect(1500, 230, 71, 20))
        self.comboBoxsutlukahve.setObjectName("comboBoxsutlukahve")
        self.comboBoxsutlukahve.addItem("")
        self.comboBoxsutlukahve.addItem("")
        self.comboBoxsutlukahve.addItem("")
        self.comboBoxsutlukahve.addItem("")
        self.comboBoxsutlukahve.addItem("")
        self.comboBoxdibek = QtWidgets.QComboBox(menu)
        self.comboBoxdibek.setGeometry(QtCore.QRect(1500, 190, 71, 20))
        self.comboBoxdibek.setObjectName("comboBoxdibek")
        self.comboBoxdibek.addItem("")
        self.comboBoxdibek.addItem("")
        self.comboBoxdibek.addItem("")
        self.comboBoxdibek.addItem("")
        self.comboBoxdibek.addItem("")
        self.comboBoxspecial = QtWidgets.QComboBox(menu)
        self.comboBoxspecial.setGeometry(QtCore.QRect(1530, 550, 71, 20))
        self.comboBoxspecial.setObjectName("comboBoxspecial")
        self.comboBoxspecial.addItem("")
        self.comboBoxspecial.addItem("")
        self.comboBoxspecial.addItem("")
        self.comboBoxspecial.addItem("")
        self.comboBoxspecial.addItem("")
        self.comboBoxicetea = QtWidgets.QComboBox(menu)
        self.comboBoxicetea.setGeometry(QtCore.QRect(1460, 510, 71, 20))
        self.comboBoxicetea.setObjectName("comboBoxicetea")
        self.comboBoxicetea.addItem("")
        self.comboBoxicetea.addItem("")
        self.comboBoxicetea.addItem("")
        self.comboBoxicetea.addItem("")
        self.comboBoxicetea.addItem("")
        self.comboBoxmadensuyu = QtWidgets.QComboBox(menu)
        self.comboBoxmadensuyu.setGeometry(QtCore.QRect(1460, 420, 71, 20))
        self.comboBoxmadensuyu.setObjectName("comboBoxmadensuyu")
        self.comboBoxmadensuyu.addItem("")
        self.comboBoxmadensuyu.addItem("")
        self.comboBoxmadensuyu.addItem("")
        self.comboBoxmadensuyu.addItem("")
        self.comboBoxmadensuyu.addItem("")
        self.comboBoxdamlasakizli = QtWidgets.QComboBox(menu)
        self.comboBoxdamlasakizli.setGeometry(QtCore.QRect(1590, 310, 71, 20))
        self.comboBoxdamlasakizli.setObjectName("comboBoxdamlasakizli")
        self.comboBoxdamlasakizli.addItem("")
        self.comboBoxdamlasakizli.addItem("")
        self.comboBoxdamlasakizli.addItem("")
        self.comboBoxdamlasakizli.addItem("")
        self.comboBoxdamlasakizli.addItem("")
        self.comboBoxmeyvelisoda = QtWidgets.QComboBox(menu)
        self.comboBoxmeyvelisoda.setGeometry(QtCore.QRect(1460, 470, 71, 20))
        self.comboBoxmeyvelisoda.setObjectName("comboBoxmeyvelisoda")
        self.comboBoxmeyvelisoda.addItem("")
        self.comboBoxmeyvelisoda.addItem("")
        self.comboBoxmeyvelisoda.addItem("")
        self.comboBoxmeyvelisoda.addItem("")
        self.comboBoxmeyvelisoda.addItem("")
        self.btntoplam = QtWidgets.QPushButton(menu)
        self.btntoplam.setGeometry(QtCore.QRect(1260, 850, 171, 51))
        self.btntoplam.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
                                     "background-color:rgb(88, 25, 31);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "border-bottom-color: rgb(115, 14, 18);")
        self.btntoplam.setObjectName("btntoplam")
        self.buttonBox = QtWidgets.QDialogButtonBox(menu)
        self.buttonBox.setGeometry(QtCore.QRect(1560, 900, 191, 51))
        self.buttonBox.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
                                     "background-color:rgb(88, 25, 31);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "border-bottom-color: rgb(115, 14, 18);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_13 = QtWidgets.QLabel(menu)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 1921, 51))
        self.label_13.setStyleSheet("font: 75 italic 20pt \"Palatino Linotype\";\n"
                                    "background-color: rgb(78, 52, 59);\n"
                                    "color: rgb(245, 250, 246);")
        self.label_13.setObjectName("label_13")
        self.lblToplamFiyati = QtWidgets.QLabel(menu)
        self.lblToplamFiyati.setGeometry(QtCore.QRect(1290, 900, 111, 41))
        self.lblToplamFiyati.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
                                    "background-color:rgb(88, 25, 31);\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "border-bottom-color: rgb(115, 14, 18);")
        self.lblToplamFiyati.setObjectName("lblToplamFiyati")
        self.label_15 = QtWidgets.QLabel(menu)
        self.label_15.setGeometry(QtCore.QRect(1560, 850, 191, 51))
        self.label_15.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
                                    "background-color:rgb(88, 25, 31);\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "border-bottom-color: rgb(115, 14, 18);")
        self.label_15.setObjectName("label_15")
        self.pushButtonAdd = QtWidgets.QPushButton(menu)
        self.pushButtonAdd.setGeometry(QtCore.QRect(1270, 770, 141, 51))
        self.pushButtonAdd.setStyleSheet("background-color: rgb(85, 0, 0);\n"
                                         "font: 75 11pt \"Segoe Script\";\n"
                                         "color: rgb(255, 255, 255);")
        self.pushButtonAdd.setObjectName("pushButtonAdd")

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)
        mycheckBox = [self.checkBoxsutlac, self.checkBoxtrilece, self.checkBoxgullac, self.checkBoxmuhallebi,
                      self.checkBoxkazandibi, self.checkBoxmagnolia, self.checkBoxirmik, self.checkBoxprof,
                      self.checkBoxspungle, self.checkBoxkeskul,
                      self.checkBoxcevizli, self.checkBoxfindikli, self.checkBoxnuriye, self.checkBoxsobiyet,
                      self.checkBoxfkadayif, self.checkBoxkdolma, self.checkBoxkatmer, self.checkBoxekmek,
                      self.checkBoxkaymak,
                      self.checkBoxfcake, self.checkBoxlcake, self.checkBoxbrowni, self.checkBoxmozaik,
                      self.checkBoxkuruvasan, self.checkBoxtiramisu, self.checkBoxfistikryasi,
                      self.checkBoxmeyvesoleni,
                      self.checkBoxcikolatalim, self.checkBoxozelpasta,
                      self.checkBoxcay, self.checkBoxturkkahvesi, self.checkBoxdibek, self.checkBoxdamlasakizli,
                      self.checkBoxsutlukahve, self.checkBox_38, self.checkBoxmadensuyu,
                      self.checkBoxmeyvelisoda,
                      self.checkBoxicetea, self.checkBoxspecial]

        mycombokBox = [self.comboBoxsutlac, self.comboBoxtrilece, self.comboBoxgullac, self.comboBoxmuhallebi,
                       self.comboBoxkazandibi, self.comboBoxmagnolia, self.comboBoxirmik, self.comboBoxprof,
                       self.comboBoxspungle, self.comboBoxkeskul,
                       self.comboBoxcevizli, self.comboBoxfindikli, self.comboBoxnuriye, self.comboBoxsobiyet,
                       self.comboBoxfkadayif, self.comboBoxkdolma, self.comboBoxkatmer, self.comboBoxekmek,
                       self.comboBoxkaymak,
                       self.comboBoxfcake, self.comboBoxlcake, self.comboBoxbrowni, self.comboBoxmozaik,
                       self.comboBoxkuruvasan, self.comboBoxtiramisu, self.comboBoxfistikruyasi,
                       self.comboBoxmeyvesoleni, self.comboBoxcikolatalim, self.comboBoxozelpasta,
                       self.comboBoxcay, self.comboBoxturkkahvesi, self.comboBoxdibek,
                       self.comboBoxdamlasakizli,
                       self.comboBoxsutlukahve, self.comboBox_38, self.comboBoxmadensuyu,
                       self.comboBoxmeyvelisoda,
                       self.comboBoxicetea, self.comboBoxspecial]


    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "Form"))
        self.checkBoxgullac.setText(_translate("menu", "Güllaç"))
        self.checkBoxirmik.setText(_translate("menu", "Sütlü irmik helvası"))
        self.label.setText(_translate("menu", "Sütlüler ☻"))
        self.checkBoxkazandibi.setText(_translate("menu", "Kazandibi"))
        self.checkBoxprof.setText(_translate("menu", "Profiterol"))
        self.checkBoxspungle.setText(_translate("menu", "Spungle"))
        self.checkBoxmagnolia.setText(_translate("menu", "Magnolia"))
        self.checkBoxmuhallebi.setText(_translate("menu", "Muhallebi"))
        self.checkBoxsutlac.setText(_translate("menu", "Fırında Sütlaç"))
        self.checkBoxtrilece.setText(_translate("menu", "Trileçe"))
        self.label_sutluler.setText(_translate("menu", "Porsiyon: ₺ 20"))
        self.checkBoxkeskul.setText(_translate("menu", "Keşkül"))
        self.comboBoxmagnolia.setItemText(0, _translate("menu", "1"))
        self.comboBoxmagnolia.setItemText(1, _translate("menu", "2"))
        self.comboBoxmagnolia.setItemText(2, _translate("menu", "3"))
        self.comboBoxmagnolia.setItemText(3, _translate("menu", "4"))
        self.comboBoxmagnolia.setItemText(4, _translate("menu", "5"))
        self.comboBoxirmik.setItemText(0, _translate("menu", "1"))
        self.comboBoxirmik.setItemText(1, _translate("menu", "2"))
        self.comboBoxirmik.setItemText(2, _translate("menu", "3"))
        self.comboBoxirmik.setItemText(3, _translate("menu", "4"))
        self.comboBoxirmik.setItemText(4, _translate("menu", "5"))
        self.comboBoxprof.setItemText(0, _translate("menu", "1"))
        self.comboBoxprof.setItemText(1, _translate("menu", "2"))
        self.comboBoxprof.setItemText(2, _translate("menu", "3"))
        self.comboBoxprof.setItemText(3, _translate("menu", "4"))
        self.comboBoxprof.setItemText(4, _translate("menu", "5"))
        self.comboBoxspungle.setItemText(0, _translate("menu", "1"))
        self.comboBoxspungle.setItemText(1, _translate("menu", "2"))
        self.comboBoxspungle.setItemText(2, _translate("menu", "3"))
        self.comboBoxspungle.setItemText(3, _translate("menu", "4"))
        self.comboBoxspungle.setItemText(4, _translate("menu", "5"))
        self.comboBoxkeskul.setItemText(0, _translate("menu", "1"))
        self.comboBoxkeskul.setItemText(1, _translate("menu", "2"))
        self.comboBoxkeskul.setItemText(2, _translate("menu", "3"))
        self.comboBoxkeskul.setItemText(3, _translate("menu", "4"))
        self.comboBoxkeskul.setItemText(4, _translate("menu", "5"))
        self.comboBoxsutlac.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxsutlac.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxsutlac.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxsutlac.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxsutlac.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxtrilece.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxtrilece.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxtrilece.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxtrilece.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxtrilece.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxgullac.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxgullac.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxgullac.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxgullac.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxgullac.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxmuhallebi.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxmuhallebi.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxmuhallebi.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxmuhallebi.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxmuhallebi.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxkazandibi.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxkazandibi.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxkazandibi.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxkazandibi.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxkazandibi.setItemText(4, _translate("menu", "5 adet"))
        self.checkBoxfindik.setText(_translate("menu", "fındık"))
        self.checkBoxbeyazcikolata.setText(_translate("menu", "beyaz çikolata"))
        self.checkBoxcilek.setText(_translate("menu", "çilek"))
        self.checkBoxfndkezmesi.setText(_translate("menu", "fındık ezmesi"))
        self.checkBoxkivi.setText(_translate("menu", "kivi"))
        self.checkBoxmuz.setText(_translate("menu", "muz"))
        self.checkBoxframbuaz.setText(_translate("menu", "Frambuaz"))
        self.checkBoxbal.setText(_translate("menu", "bal"))
        self.checkBoxhindistan.setText(_translate("menu", "h. cevizi"))
        self.checkBoxvisne.setText(_translate("menu", "vişne"))
        self.checkBoxceviz.setText(_translate("menu", "ceviz"))
        self.checkBoxbittercik.setText(_translate("menu", "bitter çikolata"))
        self.checkBoxnutella.setText(_translate("menu", "nutella"))
        self.checkBoxdondurma.setText(_translate("menu", "dondurma(vanilya)"))
        self.label_3.setText(_translate("menu", "Waffle☻ "))
        self.checkBoxfindikli.setText(_translate("menu", "Fındıklı Baklava"))
        self.checkBoxfkadayif.setText(_translate("menu", "Fıstıklı kadayıf"))
        self.checkBoxfistikli.setText(_translate("menu", "Fıstıklı Baklava"))
        self.checkBoxkunefe.setText(_translate("menu", "Künefe"))
        self.checkBoxkdolma.setText(_translate("menu", "Kadayıf Dolması"))
        self.checkBoxsobiyet.setText(_translate("menu", "Şöbiyet"))
        self.checkBoxkatmer.setText(_translate("menu", "Katmer"))
        self.checkBoxnuriye.setText(_translate("menu", "Sütlü Nuriye"))
        self.checkBoxcevizli.setText(_translate("menu", "Cevizli Baklava"))
        self.checkBoxcikobak.setText(_translate("menu", "Çikolatalı Baklava"))
        self.checkBoxkaymak.setText(_translate("menu", "Kaymak (+ ₺3)"))
        self.checkBoxekmek.setText(_translate("menu", "Ekmek Kadayıfı"))
        self.comboBoxcevizli.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxcevizli.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxcevizli.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxcevizli.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxcevizli.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxfistikli.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxfistikli.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxfistikli.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxfistikli.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxfistikli.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxfindikli.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxfindikli.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxfindikli.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxfindikli.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxfindikli.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxnuriye.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxnuriye.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxnuriye.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxnuriye.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxnuriye.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxsobiyet.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxsobiyet.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxsobiyet.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxsobiyet.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxsobiyet.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxcikobak.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxcikobak.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxcikobak.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxcikobak.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxcikobak.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxfkadayif.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxfkadayif.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxfkadayif.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxfkadayif.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxfkadayif.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxkdolma.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxkdolma.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxkdolma.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxkdolma.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxkdolma.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxkatmer.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxkatmer.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxkatmer.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxkatmer.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxkatmer.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxekmek.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxekmek.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxekmek.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxekmek.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxekmek.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxkunefe.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxkunefe.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxkunefe.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxkunefe.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxkunefe.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxkaymak.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxkaymak.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxkaymak.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxkaymak.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxkaymak.setItemText(4, _translate("menu", "5 adet"))
        self.label_6.setText(_translate("menu", "  Şerbetliler ☻"))
        self.label_serbetliler.setText(_translate("menu", " Porsiyon: ₺ 25"))
        self.label_5.setText(_translate("menu", "Waffle alana çay ikramımızdır☻  "))
        self.label_waffle.setText(_translate("menu", "  Porsiyon: ₺ 25"))
        self.label_8.setText(_translate("menu", "Waffle☻ "))
        self.label_pastalar.setText(_translate("menu", "  Porsiyon: ₺ 20"))
        self.checkBoxlcake.setText(_translate("menu", "Limonlu Cheescake"))
        self.checkBoxtiramisu.setText(_translate("menu", "Tiramisu"))
        self.checkBoxfistikryasi.setText(_translate("menu", "Fıstık Rüyası"))
        self.checkBoxmozaik.setText(_translate("menu", "Mozaik Pasta"))
        self.checkBoxmeyvesoleni.setText(_translate("menu", "Meyve Şöleni"))
        self.checkBoxbrowni.setText(_translate("menu", "Browni"))
        self.checkBoxfcake.setText(_translate("menu", "Framboazlı Cheescake"))
        self.checkBoxkuruvasan.setText(_translate("menu", "Kuruvasan"))
        self.checkBoxcikolatalim.setText(_translate("menu", "Çikolatalım"))
        self.comboBoxfcake.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxfcake.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxfcake.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxfcake.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxfcake.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxlcake.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxlcake.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxlcake.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxlcake.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxlcake.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxbrowni.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxbrowni.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxbrowni.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxbrowni.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxbrowni.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxmozaik.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxmozaik.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxmozaik.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxmozaik.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxmozaik.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxkuruvasan.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxkuruvasan.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxkuruvasan.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxkuruvasan.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxkuruvasan.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxmeyvesoleni.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxmeyvesoleni.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxmeyvesoleni.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxmeyvesoleni.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxmeyvesoleni.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxcikolatalim.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxcikolatalim.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxcikolatalim.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxcikolatalim.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxcikolatalim.setItemText(4, _translate("menu", "5 adet"))
        self.label_11.setText(_translate("menu", "Pastalar"))
        self.checkBoxozelpasta.setText(_translate("menu", "Özel Pasta  (₺ 60) "))
        self.checkBoxcay.setText(_translate("menu", "Çay  ₺3"))
        self.checkBoxdamlasakizli.setText(_translate("menu", "Damla Sakızlı Türk Kahvesi"))
        self.checkBoxdibek.setText(_translate("menu", "Dibek Kahvesi  ₺15"))
        self.checkBoxturkkahvesi.setText(_translate("menu", "Türk Kahvesi  ₺12"))
        self.label_12.setText(_translate("menu", "İçecekler"))
        self.checkBoxsutlukahve.setText(_translate("menu", "Sütlü Kahve  ₺15"))
        self.checkBoxmadensuyu.setText(_translate("menu", "Maden Suyu  ₺4"))
        self.checkBox_38.setText(_translate("menu", "Sıcak Çikolata  ₺15"))
        self.checkBoxmeyvelisoda.setText(_translate("menu", "Meyveli Soda  ₺5"))
        self.checkBoxicetea.setText(_translate("menu", "Ice Tea  ₺5"))
        self.checkBoxspecial.setText(_translate("menu", "Special Meyve Suyu  ₺15"))
        self.comboBox_waffle.setItemText(0, _translate("menu", "1 adet"))
        self.comboBox_waffle.setItemText(1, _translate("menu", "2 adet"))
        self.comboBox_waffle.setItemText(2, _translate("menu", "3 adet"))
        self.comboBox_waffle.setItemText(3, _translate("menu", "4 adet"))
        self.comboBox_waffle.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxtiramisu.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxtiramisu.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxtiramisu.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxtiramisu.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxtiramisu.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxfistikruyasi.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxfistikruyasi.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxfistikruyasi.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxfistikruyasi.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxfistikruyasi.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxozelpasta.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxozelpasta.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxozelpasta.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxozelpasta.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxozelpasta.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxcay.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxcay.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxcay.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxcay.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxcay.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxturkkahvesi.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxturkkahvesi.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxturkkahvesi.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxturkkahvesi.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxturkkahvesi.setItemText(4, _translate("menu", "5 adet"))
        self.comboBox_38.setItemText(0, _translate("menu", "1 adet"))
        self.comboBox_38.setItemText(1, _translate("menu", "2 adet"))
        self.comboBox_38.setItemText(2, _translate("menu", "3 adet"))
        self.comboBox_38.setItemText(3, _translate("menu", "4 adet"))
        self.comboBox_38.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxsutlukahve.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxsutlukahve.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxsutlukahve.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxsutlukahve.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxsutlukahve.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxdibek.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxdibek.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxdibek.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxdibek.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxdibek.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxspecial.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxspecial.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxspecial.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxspecial.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxspecial.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxicetea.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxicetea.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxicetea.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxicetea.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxicetea.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxmadensuyu.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxmadensuyu.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxmadensuyu.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxmadensuyu.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxmadensuyu.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxdamlasakizli.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxdamlasakizli.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxdamlasakizli.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxdamlasakizli.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxdamlasakizli.setItemText(4, _translate("menu", "5 adet"))
        self.comboBoxmeyvelisoda.setItemText(0, _translate("menu", "1 adet"))
        self.comboBoxmeyvelisoda.setItemText(1, _translate("menu", "2 adet"))
        self.comboBoxmeyvelisoda.setItemText(2, _translate("menu", "3 adet"))
        self.comboBoxmeyvelisoda.setItemText(3, _translate("menu", "4 adet"))
        self.comboBoxmeyvelisoda.setItemText(4, _translate("menu", "5 adet"))
        self.btntoplam.setText(_translate("menu", "TOPLAM FİYAT"))
        self.label_13.setText(_translate("menu",
                                         "                                                                                     ~~ TADIGÜZEL PASTANELERİ ~~"))
        self.lblToplamFiyati.setText(_translate("menu", " :"))
        self.label_15.setText(_translate("menu", " Siparişi Tamamla!"))
        self.label_2.setText(_translate("menu", "TextLabel"))
        self.label_4.setText(_translate("menu", "TextLabel"))
        self.pushButtonAdd.setText(_translate("menu", "Siparişe Ekle"))
        self.checkBoxsutlac.clicked.connect(lambda: self.fiyat(1))

    def fiyat(self, id):
        price = self.getPriceSutluler(id)
        print(str(price))
        n = self.comboBoxsutlac.currentIndex() + 1
        total = price * n
        self.lblToplamFiyati.setText('%0.2f' % total)

    def getPriceSutluler(self, id):
        conn = sqlite3.connect('Our_data.db')
        curs = conn.cursor()
        content = 'select fiyat from Sutluler where sutluid= %d' % id
        res = curs.execute(content)
        for data in res:
            return data[0]


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    menu = QtWidgets.QWidget()
    ui = Ui_menu()
    ui.setupUi(menu)
    menu.show()
    sys.exit(app.exec_())
